### ISSUE TITLE
Nested reader conditional has redundant cljs branch

### ISSUE THREAD

**Issue by rgould1** [kkinnear/zprint#110]
https://github.com/kkinnear/zprint/blob/543a9783ba59c2822c7a12bff84b40b21eb87a93/src/zprint/core.cljc#L158

Figwheel is complaining about unbounded function `js/Error.`. Believe this is a result of the nested reader conditional, so that the :cljs branch is not necessary.

**Comment by kkinnear** [comment]
Thanks for figuring this out.  I do test with Figwheel, but only when I release (which isn't that often, recently).  I will fix this in the upcoming release (which is coming pretty soon).  Thanks again!

**Comment by rgould1** [comment]
Great, thanks for that.

**Comment by kkinnear** [comment]
Thanks for input, this is fixed in 0.5.0.
