### ISSUE TITLE
Config via URL

### ISSUE THREAD

**Issue by coltnz** [kkinnear/zprint#112]
Hi, we'd like to have 1 canonical config across all our projects. Are you open to a pull request recognising a URL arg as 'the third way' and resolving that as the config? 

cheers
Colin

**Comment by kkinnear** [comment]
What an interesting idea! I am open to this idea as long as it doesn't add dependencies to the basic zprint library (which I don't believe that it would need to do).  I'm assuming that to access this capability you would use a switch on the uberjar or graalVM binaries to specify the URL?  I suppose that it could be available to the library/REPL as well, though that seems distant from what I imagine your actual use case to be.

I'm thinking that you would want this to be the *only* configuration used when it was specified, as opposed to also accessing the users `~/.zprintrc`.  I have just implemented that sort of "ignore any other configuration" capability for the new 0.5.0 "--default" switch.  Which was done as a bit of a special case.  I'm thinking that it might be time for some more general options map configuration that would say "this is the only configuration, ignore anything else but what is in __this__ options map".  Which you could use in your canonical configuration access by the URL.

But I'm probably getting ahead things here.  Yes, I'm interested, and I would like to hear more about your actual use case and how you are thinking that you would go about implementing this, particularly the UI -- how a user would specify the URL.

Thanks for asking!

**Comment by coltnz** [comment]
A few comments:
- no deps for sure
- yep I expected I'd add to all zprint entry points
- our use case is definitely a remote config as the only config. I can see remote only/remote+local/local+remote all as valid options but 1 thing at a time perhaps :)
- a ttl-cache might be required

**Comment by coltnz** [comment]
#117

**Comment by kkinnear** [comment]
Thanks for the implementation!  The code was released in 0.5.4.
