### ISSUE TITLE
Use zprint-filter to colorise output

### ISSUE THREAD

**Issue by gphilipp** [kkinnear/zprint#113]
From what I understand you can pretty-print very quickly an EDN form, but there's no option to use `czprint` to have a colorised output. Am I missing something ?

**Comment by kkinnear** [comment]
You are correct, the uberjar (and the zprint-filters built from it) assume that you are outputting to a file and don't include ANSI terminal escapes for color.  I don't think it would be all that difficult for me to change this so that you could specify `{:color? true}` in the options map to produce output with ANSI escape sequences embedded in it.  

Is that actually what you are looking for -- output with ANSI escape sequences included?  This will look colored on a "terminal" which supports these escape sequences, but be garbage in pretty much any other context.

**Comment by gphilipp** [comment]
It’s exactly the use case. The use case is that sometime we have raw edn data in Kafka topics and I use zprint filter at the command line to print these messages. Having them in color would even be better. So the option would be perfect. Alternatively an arg at the command line would work too: `zprint —color=true`

> On 28 Oct 2019, at 17:55, Kim Kinnear <notifications@github.com> wrote:
> 
> ﻿
> You are correct, the uberjar (and the zprint-filters built from it) assume that you are outputting to a file and don't include ANSI terminal escapes for color. I don't think it would be all that difficult for me to change this so that you could specify {:color? true} in the options map to produce output with ANSI escape sequences embedded in it.
> 
> Is that actually what you are looking for -- output with ANSI escape sequences included? This will look colored on a "terminal" which supports these escape sequences, but be garbage in pretty much any other context.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 






Funding Circle Limited is authorised and regulated by the Financial 
Conduct Authority under firm registration number 722513. Funding Circle is 
not covered by the Financial Services Compensation Scheme. Registered in 
England (Co. No. 06968588) with registered office at 71 Queen Victoria 
Street, London EC4V 4AY.

**Comment by kkinnear** [comment]
You are in luck.  I was just about to release a bug-fix for 0.5.0, and I had a long plane flight, and so I implemented what you need for this issue.  If you specify an options map of `{:color? true}` for any of the uberjar or graalVM binaries, you will get ANSI escape sequence colorized output.  __DO NOT__ put this into  your `$HOME/.zprintrc`, or any code that you format with these utilities will also contain the escape sequences.

**Comment by gphilipp** [comment]
Great ! So you passed it as a command line arg as in `zprint  {:color? true}` ?

> On 29 Oct 2019, at 18:02, Kim Kinnear <notifications@github.com> wrote:
> 
> ﻿
> You are in luck. I was just about to release a bug-fix for 0.5.0, and I had a long plane flight, and so I implemented what you need for this issue. If you specify an options map of {:color? true} for any of the uberjar or graalVM binaries, you will get ANSI escape sequence colorized output. DO NOT put this into your $HOME/.zprintrc, or any code that you format with these utilities will also contain the escape sequences.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 






Funding Circle Limited is authorised and regulated by the Financial 
Conduct Authority under firm registration number 722513. Funding Circle is 
not covered by the Financial Services Compensation Scheme. Registered in 
England (Co. No. 06968588) with registered office at 71 Queen Victoria 
Street, London EC4V 4AY.

**Comment by kkinnear** [comment]
Yes

**Comment by gphilipp** [comment]
Perfect thanks !

> On 29 Oct 2019, at 19:04, Kim Kinnear <notifications@github.com> wrote:
> 
> ﻿Yes
> 
> > On Oct 29, 2019, at 2:55 PM, Gilles Philippart <notifications@github.com> wrote:
> > 
> > ﻿Great ! So you passed it as a command line arg as in `zprint {:color? true}` ?
> > 
> > > On 29 Oct 2019, at 18:02, Kim Kinnear <notifications@github.com> wrote:
> > > 
> > > ﻿
> > > You are in luck. I was just about to release a bug-fix for 0.5.0, and I had a long plane flight, and so I implemented what you need for this issue. If you specify an options map of {:color? true} for any of the uberjar or graalVM binaries, you will get ANSI escape sequence colorized output. DO NOT put this into your $HOME/.zprintrc, or any code that you format with these utilities will also contain the escape sequences.
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > -- 
> > 
> > 
> > 
> > 
> > 
> > 
> > Funding Circle Limited is authorised and regulated by the Financial 
> > Conduct Authority under firm registration number 722513. Funding Circle is 
> > not covered by the Financial Services Compensation Scheme. Registered in 
> > England (Co. No. 06968588) with registered office at 71 Queen Victoria 
> > Street, London EC4V 4AY.
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 






Funding Circle Limited is authorised and regulated by the Financial 
Conduct Authority under firm registration number 722513. Funding Circle is 
not covered by the Financial Services Compensation Scheme. Registered in 
England (Co. No. 06968588) with registered office at 71 Queen Victoria 
Street, London EC4V 4AY.
