### ISSUE TITLE
Add range formatting

### ISSUE THREAD

**Issue by agriffis** [kkinnear/zprint#122]
I've been working on https://github.com/google/vim-codefmt/pull/130

The plugin supports formatting the entire buffer or a range of lines. For the latter, we currently send zprint only the lines to be formatted. This works okay for top-level forms, but it relies on the editor to identify the lines to send, and it also misses out on any zprint comment directives that precede the region.

Ideally we'd send the entire buffer, but direct zprint to format only the desired range. For reference, here are some other formatters which support formatting a range of lines:

- https://github.com/hhatto/autopep8#usage
- https://clang.llvm.org/docs/ClangFormat.html
- https://github.com/google/google-java-format#from-the-command-line
- https://prettier.io/docs/en/options.html#range

For zprint, it may never make sense to format anything except top-level forms, so it would be reasonable to automatically extend the requested range backward and forward as necessary.

What do you think?

**Comment by kkinnear** [comment]
While I'm excited you are working on integrating zprint with vim-codefmt, I'm not sure quite what I think about your proposal until I know a bit more.  Some questions:

1. If send a whole buffer of lines to zprint and specify a range, what would you expect back?  Just the formatted range, or the whole buffer with the range formatted inside of the buffer?

2. I agree that it might not make sense to format the interior of a top level form, but having zprint figure out where the top-level form starts and ends (and including any !zprint directives) seems like it would require parsing the entire buffer.  Which isn't necessarily bad, but maybe not what you were thinking?  Is there something obvious that i'm missing here?

Thanks!

**Comment by agriffis** [comment]
> 1. If send a whole buffer of lines to zprint and specify a range, what would you expect back?  Just the formatted range, or the whole buffer with the range formatted inside of the buffer?

The whole buffer with the range formatted inside of the buffer.

> 2. I agree that it might not make sense to format the interior of a top level form, but having zprint figure out where the top-level form starts and ends (and including any !zprint directives) seems like it would require parsing the entire buffer.  Which isn't necessarily bad, but maybe not what you were thinking?  Is there something obvious that i'm missing here?

No, that sounds right to me. Zprint would need to parse the entire buffer, figure out what top-level form(s) overlap the given line range, format just those forms, and return the entire buffer. 

It's like starting the file with `;!zprint {:format :off}` and then, just prior to the forms overlapping the line range, `;!zprint {:format :on}`, then turning it back off again after the line range.

If the line range falls within an area where zprint is toggled off (either with `:format :off` or `:format :skip`) then zprint should return the buffer unchanged. In other words, specifying a line range of the entire file should work exactly the same as not specifying a line range.

Tangentially, I've also been thinking about offset mapping for cursor tracking. It would be really interesting to pass in a line and column, and have zprint return (perhaps on stderr) the appropriate line and column considering the reformatting. That would make it possible to use zprint asynchronously to reformat live while editing instead of waiting for explicit command or save. For flexibility, it should work with multiple offsets, to support selection start/end, multiple cursors, etc.

But that's future stuff. For now it would be great to just have range formatting :grin:

**Comment by kkinnear** [comment]
I'm still pondering the range formatting.  The cursor mapping has been asked for by someone else, see Issue #119.   I've been thinking a lot about how to do that, and I have some ideas but nothing that I've had time to actually try out in practice.  More on this later.

**Comment by kkinnear** [comment]
Having just released 0.5.4, I'm now giving this a closer look. I seem to have found a parser that I can use to figure out where the top level forms fall in the file that is about 3 times faster than the regular zprint parser (rewrite-clj).  So, I think I can maybe make all of this work.  At the cost of another dependency, which I've been trying to limit.  But it may well be worth it for this capability.

My question for you is: how do you expect to access this capability?
  * As a feature in the zprint library (or possibly another library that calls zprint)
  * As a main program, for instance the uberjar or one of the pre-build graalVM binaries?

I want to make sure that whatever I come up with works well in your environment.

Thanks!

**Comment by kkinnear** [comment]
I've added this capability in 1.0.0.  I hope it meets your needs -- if not, please let me know.  You can see how to use it [here](https://github.com/kkinnear/zprint/blob/master/doc/using/range.md). If the usage isn't clear, please get in touch!

Thanks for asking for what you need!
