### ISSUE TITLE
Add Utility Functions to Base New Colors on Existing Colors

### ISSUE THREAD

**Issue by RingMan** [kkinnear/zprint#142]
I wrote a few utility functions that complement that ansi-colors branch to manipulate ANSI codes and color maps.  These functions make it possible to mix in new attributes to existing colors, which lets you make things visually distinct while preserving the original theme. If you think library users would benefit, feel free to incorporate these somewhere.

```clojure
(defn merge-colors [a b]
  (cond
    (and (sequential? a) (sequential? b)) (into (vec a) b)
    (sequential? a) (into (vec a) (vector b))
    (sequential? b) (into (vector a) b)
    :else [a b]))

(defn cmap [color-map]
  {:color-map
   (merge-with merge-colors (:color-map (get-options)) color-map)})

(defn kcol [key-color]
  (let [{kw :keyword, :keys [number string]} (:color-map (get-options))]
    {:key-color
     (into {} (map (fn [[k v]]
                     (cond
                       (keyword? k) [k (merge-colors kw v)]
                       (string? k) [k (merge-colors string v)]
                       (number? k) [k (merge-colors number v)]
                       :else [k v]))
                   key-color))}))

(defn cstyle [ckeys style]
  (cmap (into {} (for [ckey ckeys] [ckey style]))))

(defn kstyle [mkeys style]
  (kcol (into {} (for [mkey mkeys] [mkey style]))))
```

Here's a short REPL session using `cmap` and `cstyle`. Both functions apply additional styling to selected elements in the current color-map. `cmap` accepts a color-map as its input. `cstyle` takes two sequences: a sequence of color-map keys and a sequence of ANSI codes to apply to those elements.

![cmap-cstyle](https://user-images.githubusercontent.com/1686741/78840627-df953200-79c0-11ea-91e3-00828428fa4a.PNG)

More REPL interaction using `kcol` and `kstyle`. These work analogously to `cmap` and `cstyle`.

![kcol-kstyle](https://user-images.githubusercontent.com/1686741/78842571-f12d0880-79c5-11ea-87ad-1038c75bb6b0.PNG)

**Comment by kkinnear** [comment]
I managed to sort of miss this when I was putting together 1.0.1.  Do you see these functions as something that would still be useful, given that I've taken all of your pull requests (pretty much as is)?  Thanks!

**Comment by RingMan** [comment]
I'm fine with closing this issue if you like. I think the idea behind these functions still has some validity, but I'm not entirely happy with their implementation. I've iterated them a time or two but don't yet have a result I'm completely satisfied with. With the changes you've folded in, I can now use these with the official zprint instead of just my fork, which is nice! You can always reopen if more users request similar functionality. For now, I think things are fine as is.

**Comment by kkinnear** [comment]
Thanks!
