### ISSUE TITLE
Datomic query formatting

### ISSUE THREAD

**Issue by bhurlow** [kkinnear/zprint#146]
I'm trying to find the right zprint settings to customize the indentation of Datomic query `:where` clauses. My desired formatting output is:

```clj
(def query-1
  [:find ?followers ?first_name ?last_name
   :in $ [?followers ...]
   :where [?followers :user/firstname ?first_name]
          [?followers :user/lastname ?last_name]])
```
namely each where clause is indented with the `:where` depth. The `:constant-pair?` setting gets close except Datomic queries can have more than a single form between the `:find`,`:in`, `:where` (and `:with`) keywords. 

Is there a way to specify these special keys and their indent behaviors?

Apologies if this has been asked before, I couldn't find any duplicates

**Comment by kkinnear** [comment]
Thanks for asking!  

One approach you could use if you define these queries at the top level, is to just turn off
formatting for them using the `;!zprint` directives.  This is kind of a hack, but does give you 
just what you want:

```clojure
;!zprint {:format :off}

(def query-1
  [:find ?followers ?first_name ?last_name
   :in $ [?followers ...]
   :where [?followers :user/firstname ?first_name]
          [?followers :user/lastname ?last_name]])

;!zprint {:format :on}
```
If all of your queries are defined at the top level, then this approach will work pretty well. 
It requires you to hand-format the queries the way you want, and then preserves that formatting.

There isn't any way that I can find to get precisely what you want using zprint formatting.  It is simple to get close (which you may have already done):
```clojure
(print i146a)
(def query-1
  [:find ?followers ?first_name ?last_name
   :in $ [?followers ...]
   :where [?followers :user/firstname ?first_name]
          [?followers :user/lastname ?last_name]])

; The above just shows you what is being formatted below:

(zprint i146a {:parse-string? true :style :keyword-respect-nl})
(def query-1
  [:find ?followers ?first_name ?last_name
   :in $ [?followers ...]
   :where [?followers :user/firstname ?first_name]
   [?followers :user/lastname ?last_name]])
```
The `:keyword-respect-nl` simply says that if a vector starts with a keyword, use `:respect-nl?` for that vector -- which means that the existing newlines in the vector are used (in addition to those added to format "correctly").  So, if you put newlines in where you want, they will still be there.  All of this you may already know, but I mention it in just in case you didn't.

As you have mentioned, getting the `[followers...]` hung with the `:where` is a challenge, one that I can see no way to accomplish with the current code.  

I am beginning to imagine an approach where, within a vector, you could associate a fn-type with each of several named keywords -- and each would then format kind of like a list with that fn-type, but inside of the vector (and without "(" or ")", of course).  In your situation, you wouldn't really need to associate a fn-type with `:find`, `:in`, or `:where` -- they would print fine if each were simply considered independent lists.  I suppose that would be an alternative approach -- just configure a vector to treat every keyword as beginning a "list" from a formatting perspective.  That would be a lot easier from a configuration perspective, and would give you what you want, I think.
Perhaps some mix of these two approaches, where you give the vector a set of keywords which, when encountered, would start formatting like a list.  That's still pretty easy to configure, and allows a lot more generality.

You would probably say something like:
```clojure
(zprint i146a {:parse-string? true :vector {:keyword-list #{:find :in :where :with}}})
(def query-1
  [:find ?followers ?first_name ?last_name
   :in $ [?followers ...]
   :where [?followers :user/firstname ?first_name]
          [?followers :user/lastname ?last_name]])
```
Maybe not just keywords, maybe anything?  Then it would be `:vector {:begin-list #{ ... }` or something like that.

Would this be useful for you?  I'm in the middle of implementing range formatting (as well as fixing a bunch of bugs I've encountered), but this would be something I could take up after the next release (which should be in the next few weeks, I expect).

**Comment by kkinnear** [comment]
I forgot to mention that you can also do this to turn off formatting for a single top-level expression:
```clojure
;!zprint {:format :skip}

(def query-1
  [:find ?followers ?first_name ?last_name
   :in $ [?followers ...]
   :where [?followers :user/firstname ?first_name]
          [?followers :user/lastname ?last_name]])

```
This will cause formatting to be off for just the next top level expression.  You can see the entire ensemble of `;!zprint` directives here: https://github.com/kkinnear/zprint/blob/master/doc/bang.md

**Comment by bhurlow** [comment]
thanks for the great response! I was thinking along the same lines as you, some way of applying a formatting fn to all elements in between some user defined keywords – that would work great for me. Thankfully the keywords for Datomic queries are finite and known. 

Another idea I was curious about was if it's possible to dispatch some arbitrary user code based on the first element of a vector. In my case I can be confident that all vectors that start with `:find` can be formatted as Datomic queries, and I would be fine with manually handling the formatting of that form specifically. I'm sure there are some challenges with this.

I didn't know about the `;!zprint` option, that's very handy. Unfortunately this won't work for my specific case as I have many files across our codebase that would all need these types of annotations. 

In any case I appreciate the effort, this is a very wide configuration space

**Comment by TimoKramer** [comment]
Is it possible to specify in the .zprintrc that I don't want certain functions to be formatted?
```
{:fn-map {"q" :off}}
```

**Comment by kkinnear** [comment]
Sure, you are very close.  This will do it:
```clojure
{:fn-map {“q” :none}}
```

Thanks for asking!
