### ISSUE TITLE
Fail on Clojurescript values: `##NaN`, `##Inf`, `##-Inf`

### ISSUE THREAD

**Issue by kkinnear** [kkinnear/zprint#153]
Turns out that the rewrite-clj parser doesn't accept any of the Clojurescript elements: `##NaN`, `##Inf`, and `##-Inf`.  Thus, zprint doesn't handle these well.  There is a project underway, `rewrite-cljc` which unifies the `-clj` and `-cljs` parsers, which also handles these elements correctly.  The present plan is to wait for this parser to see the light of day to solve this problem.

An alternative would be to replace all of these elements with something else, format the file, and then restore them.  But this would be cause performance to drop and bring some other challenges, so for now we wait.

**Comment by arichiardi** [comment]
Hi Kim, yes I bumped into this on the Clojure side as well. The workaround you describe is doable only locally, in CI it would be a pain to implement.

**Comment by kkinnear** [comment]
This will be fixed in 1.2.0 which will feature the new rewrite-clj V1 parser (which is what rewrite-clic is called, as it happens).  I have integrated the parser and it works well, I have some more things to fix before I release, but this is coming sooner rather than later.

**Comment by arichiardi** [comment]
As a side note, I tried `;!zprint {:format :off}` but the exception seems to be triggered before that. I guess it makes sense for a reader macro error.

**Comment by arichiardi** [comment]
@kkinnear is there a binary preview of `1.2.0`? We would love to try it out cause this error affects our formatting and we needed to disable our code quality check in CI?

**Comment by kkinnear** [comment]
I should probably be able to generate something for you to use.  1.2.0 is largely complete from a code standpoint, though I have not finished all of my testing.  It does pass the 1300+ cli tests at present, so it isn't complete broken.  I haven't generated a binary in a while, so that may show something up.

The big question is: which binary do you use?  Mac or Linux?  I hope the Mac one, because it is way easier to generate.  The Linux one is a challenge every time, but I could probably pull that together if necessary.  I won't be able to do either until Thursday, but I will have some time to devote to this if you tell me which version you use.  I will need to know before 10am EDT Wednesday morning if you need the Linux version, as it happens.

**Comment by arichiardi** [comment]
Hey Kim, well I will start saying that if too much work, don't worry about it, I thought you had something running in CI. If not maybe I could contribute something there, I am pretty familiar with CircleCI.
We run linux boxes ourselves...cause you asked 😃
Thanks again!

**Comment by kkinnear** [comment]
CI is great, but I haven't invested in setting it up.  Yet?

In any case, let me give the Linux build a spin on Thursday, and if I can whack it into shape, then I'll send you something.  It has to be made to work anyway, so I might as well do it now when it will help you out.  I'll let you know on Thursday how it is going, one way or the other.

**Comment by kkinnear** [comment]
I'm even more interested in your configuration this point!  

I've just run 11K lines of the zprint source code through zprint 1.1.2 and 1.2.0, and found exactly zero differences.  Now, maybe I just don't do what your code does.  I think that it is entirely possible that your configuration would cause some of the zprint source to format differently in 1.2.0 from 1.1.2.  If you have a chance, I'd love to see your zprint configuration.  I'm still also interested in any code that you can share that formats differently, in case using your configuration with my code doesn't result in similar differences.  Thanks!

**Comment by arichiardi** [comment]
Will definitely send something over, thanks Kim as you remember my configuration is very unique 😃

**Comment by kkinnear** [comment]
Fixed in `1.2.0`.
