### ISSUE TITLE
How to format maps inside a map on a new line, but keep plain keys/values on same line?

### ISSUE THREAD

**Issue by hoxu** [kkinnear/zprint#157]
Example:

```clojure
{:key1 :value :key2 :value :amap {:key1 :value :key2 :value}}
```

Result:

```clojure
{:amap
 {:key1 :value
  :key2 :value}

 :key1 :value
 :key2 :value}
```

This would be useful with large maps inside a map, similar to this style:

https://github.com/seancorfield/dot-clojure/blob/c4473980603fec0577f1b7b93dde660646f73208/deps.edn#L195-L200

**Comment by kkinnear** [comment]
Thanks for asking!  With only one example I'm not sure that I fully understand what you are trying to get zprint to do, but here is my best guess at this point:

```clojure
(def i157a {:key1 :value :key2 :value :amap {:key1 :value :key2 :value}})

(czprint i157a {:map {:force-nl? true :hang? false}})
{:amap
   {:key1 :value,
    :key2 :value},
 :key1 :value,
 :key2 :value}
```
If you want the blank line after every complex map that flows (which is the technical term for what the value of `:amap` did), then try this:
```clojure
(czprint i157a {:map {:force-nl? true :hang? false :nl-separator? true}})
{:amap
   {:key1 :value,
    :key2 :value},

 :key1 :value,
 :key2 :value}
```
If one of these isn't what you want, send me some more examples and I'll see what I can figure out.

**Comment by hoxu** [comment]
Thanks for the quick reply! In the end I used this configuration:

```clojure
{:map {:comma? false
       :force-nl? true
       :hang? false
       :indent 0
       :nl-separator? true
       :sort-in-code? true}
 :width 1000}
```
