### ISSUE TITLE
Struggling to understand "Controlling Single and Multi-line Output"

### ISSUE THREAD

**Issue by vemv** [kkinnear/zprint#170]
Hi!

I'm struggling to understand/apply https://github.com/kkinnear/zprint/blob/7a8c0e82943a0ad87135ff749ae5795063cb0f74/doc/reference.md#controlling-single-and-multi-line-output.

My use case is fairly simple, so let me explain it with sample inputs and desired outputs:

```clj
;; input
(zprint.core/zprint-file-str "(defn foo [] 1 2 3 4 5)" "")

;; expected: 1 newline per sexpr within a defn arity's body
(defn foo []
  1
  2
  3
  4
  5)
```

```clj
;; input
(zprint.core/zprint-file-str "(defn foo ([] 1) ([a] 1))" "")

;; expected: 1 newline per arity
(defn foo
  ([]
   1)

  ([a]
   1))
```

```clj
;; input
(zprint.core/zprint-file-str "(defn foo ([] 1 2 3 4 5) ([a] 1))" "")

;; expected: that the two use cases above compose well
(defn foo
  ([]
   1
   2
   3
   4
   5)
  
  ([a]
   1))
```

I can never get `zprint.core/zprint-file-str` to print something similar to what I want.

The overall philosophy is to give to certain elements a fixed implication of a newline  (e.g. 1 arity = 1 newline), completely disregarding whether something would fit in one line.

Thanks - V

**Comment by kkinnear** [comment]
Thanks for making the examples simple, and for asking again.  I have some questions before I can realistically answer your question(s).

Do you really want this?
```
;; expected: that the two use cases above compose well
(defn foo
  ([]
   (1
    a
    (b
     c
     d))
   2
   3
   4
   5)
  
  ([a]
   1))
```
That is to say -- do you really want one element per line?  Never having two elements on one line?

....................

You said: 

> The overall philosophy is to give to certain elements a fixed implication of a newline (e.g. 1 arity = 1 newline), completely disregarding whether something would fit in one line.

which implies to me that you want a newline associated with some "elements".  What elements in your examples did you want newlines associated with?  That's isn't how zprint thinks about newlines today, as it happens, but it is an interesting approach that might be worth pursuing -- but I'd like to better understand your thinking before I go down that path too far.

...............

My last question is -- how are you expecting to use zprint?  There are two ways -- one way is to enforce a formatting style, where zprint ignores the formatting of the input and, using the configuration, creates the formatted output.  The second way people use zprint is to format source, but allow zprint to use some of the formatting on the input to inform how it formats the output.  For instance, there is a relatively new capability -- "respect blank lines", that will format everything as specified by the configuration but will leave any blank lines it encounters in the incoming source in the formatted output.  Which would be one way to get the output you want.  

zprint now has the capability to leave *every* newline in the input in the output, essentially ensuring that it will never bring two things that start out on different lines onto the same line.  It will split a line if it gets too long, but it will never join lines together.  But it will format and indent and do all of the other things that it does given the existing line breaks.

If you are open to the idea that the input format could inform the output format, then I can easily replicate your examples.  If not, then I have to dig a bit deeper to see what I can do for you.

Thanks for asking!

**Comment by vemv** [comment]
Hey there! Thanks so much for the quick answer

> Do you really want this?

> That is to say -- do you really want one element per line? Never having two elements on one line?

No, not really. `(b c d)` should be formatted as a single line (or as a "normal-looking function call" in any case).

Which does not contradict my original request: inner sexprs get their own rules, _after_ the surrounding defn has been laid out.

In other words. In:

```
1
2
3
4
5
```

, each of `1 2 3 4 5` (which could be as well `x y [] (foo)`) is its own world, with its own formatting independent of whatever was expressed to the surrounding defn. But at the same time, we know for sure that each element will be separated by a newline, because that was one's expectation for a defn  body.

> What elements in your examples did you want newlines associated with?

* An arity or 'tail": after each ([] ...) I expect a newline
* an arg vector: after each [] I expect a newline
* each of the expressions contained in given arity's body 
  * e.g. each of `1 2 3 4 5` gets a newline, per the previous example

...these are what I would call "the rules for defn". Other constructs could have different rules.

> My last question is -- how are you expecting to use zprint?

I have at least two lines of use cases:

* formatting existing code
  * for context, I created and keep helping with https://github.com/nedap/formatting-stack which various companies use
    * I'm happy with cljfmt (its current choice )but I sense zprint has a lot of potential for creating more fine-grained rules
* support automated refactoring of code using vanilla clojure
  * today, creating an automated refactoring tool typically involves using rewrite-clj
    * for clarity, I've used rewrite-clj multiple times successfully, I find nothing wrong with it
  * for many people, using vanilla clojure (e.g. data structure manipulation with clojure.core, clojure.walk) is more approachable than rewrrite-clj
  * my idea is: take an existing sexpr from a codebase, rewrite it with vanilla clojure, then spit a zprint-formatted version
    * without zprint, I'd have to spit e.g. `(defn [foo] 1 2 3 ...)` (e.g. no newlines) which would be pretty unreadable/problematic (worse git diffs, etc)

> If you are open to the idea that the input format could inform the output format

While I honestly think it's a neat idea (and very suitable for most use cases involving "a formatting tool"), both of my envisioned use cases have in common taking a truly arbitrary sexpr input, and emitting back a "canonically formatted" sexpr, for which indentation, newlines, etc can all be quite precisely predicted from a specific set of recursive rules.

Hope this helps!

**Comment by kkinnear** [comment]
Thanks, that helps a lot!  

I think I'm starting to understand both the context and the details of what you are trying to do.  But I'm still in need of help in understanding the details.  You said:

> > What elements in your examples did you want newlines associated with?
> 
> 1. An arity or 'tail": after each ([] ...) I expect a newline
> 2. an arg vector: after each [] I expect a newline
> 3. each of the expressions contained in given arity's body, e.g. each of 1 2 3 4 5 gets a newline, per the previous example
>
> ...these are what I would call "the rules for defn". Other constructs could have different rules.

Some additional questions:

1. I see that you want the arg vector of the `defn` on the same line as the name of the function.  Where do you want things if a docstring should appear?  
```clojure
; Do you want this (call it "A"):

(defn foo "stuff" []
 1
 2)

; or this (call it "B"):

(defn foo
 "stuff"
 []
 1
 2)

; or this (call it "C"):

(defn foo "stuff"
 []
 1
 2)

; or something else?
```
2.  In the "rules of defn" you listed above, you said that you wanted a newline after every arity expression, however in the original example you have a blank line (which is, technically, two newlines) between arity expressions. 
```clojure
;; input
(zprint.core/zprint-file-str "(defn foo ([] 1) ([a] 1))" "")

;; expected: 1 newline per arity
(defn foo
  ([]
   1)

  ([a]
   1))
```
 I confess that I often say "newline" when I really mean "blank line".  So I want to be clear here.  I see two possibilities:
  - You just want to ensure that two different arity expressions don't end up on the same line, but you don't want a blank line between them (choice "X").
  - You actually want a blank line between all arity expressions  (as in the example above)(choice "Y").

.....................
If you have been having trouble doing these things, I'm not surprised, because generally zprint won't do some of these things today.  The only "rule of defn" it has today is to put the function name on the same line as the `defn` if the whole defn doesn't fit on one line.  The rest of the formatting falls out of the flow, so the arg vector has its own line(s), and the individual expressions of a single arity function, or the arity expressions of a multiple arity function all start on their own lines.  Today zprint usually puts the arg vector of a multiple arity expression on its own line because the expression rarely fits on a single line, but if the expression together with the arg vector fits on a single line, that is how it comes out.

While I can see how I can easily create a new function type to do `defn` most of the way you want (however you answer the questions above), the most challenging thing is to put the arg vector of a multi-arity expression on its own line even if the expression would fit on a single line.  This is challenging because I'm not sure I want to do that for every list that might have a vector as its first element anywhere inside a function definition, and because when zprint processes the arity expression it doesn't know, at present, that it is one level down from a defn.  That will be a bit more problematic to figure out a clean way to make that happen.

Anyway, once I understand just what you want `defn` to do, I can better assess what I can do for you, but most of this seems pretty straightforward.  I expect that some of extending zprint to do what you want with `defn` would be specialized to a function-type, and some of it would be more generalized extensions to, say, the way that lists in general are handled.  But we'll have to see how the design falls out once I know exactly what we are trying to achieve.

Thanks for answering my questions -- It is really important to me to be sure I'm doing what someone really wants when I extend zprint, not what I imagined they wanted -- only to find out later that I missed the mark.

**Comment by vemv** [comment]
> I see that you want the arg vector of the defn on the same line as the name of the function. Where do you want things if a docstring should appear?

Personally I'd want B, which is the most frequent formatting when there's a docstring. Where there isn't one, I indeed prefer to put the argv in the same line.

> In the "rules of defn" you listed above, you said that you wanted a newline after every arity expression, however in the original example you have a blank line (which is, technically, two newlines) between arity expressions.

That's correct, you worded it better :) So, choice Y.

> If you have been having trouble doing these things, I'm not surprised, because generally zprint won't do some of these things today.

Thanks for stating this :) indeed I was unsure about zprint's capabilities.

Your final analysis seems reasonable - implementing this one shouldn't interfere with other formattings.

As some sort of caution, I have only expresed the "rules of defn" but there might be more rules as well for specifying the application of newlines. (I did notice though that things like `cond` and `let` can already be reformatted from a oneliner to something with a predictable/fixed application of newlines) It's hard to try enumerating them all in advance.

Which is to say, fixing my `defn` request might be only satisfy a certain % of my envisioned purpose, and implementing more "rules" might be more work, or might make the API/design more complex.

Of course only you can really judge :)

**Comment by kkinnear** [comment]
Thanks for helping me understand what you are looking for.

Yes, I appreciate the caution.  One thing that would help me a lot to understand your preferred formatting would be if you could point me at a repo (or even few files in a repo) that was formatted the way that you would like zprint to be able to format.  This wouldn't cover all of the cases, but it might give me a sense of the "distance" between what you want and what zprint can currently do. 

From an implementation standpoint, I'm in the final stages of releasing 1.1.0, which will take the next couple of weeks.  I am interested in trying to make zprint useful in your environment, and intend to work toward extending zprint to do what we've discussed here.  While all of that is happening, if you could point me (as I said above) at some code that is formatted the way you want zprint to be able to format code, I can look it over and try to get a feeling for the additional work involved in adapting zprint to do what you would like to see and spend some background time thinking about how much might have to change and how I might approach those changes.

Thanks!

**Comment by kkinnear** [comment]
It has been a good long while, but I have implemented an entirely new internal extension architecture in zprint release `1.1.2`, which I have just released.  I created this extension architecture specifically to be able to respond to requests such as the one you have for the "rules of defn".  Implementing the "rules of defn" as you have described them was the first thing I did with this new architecture.  I have created an new style for this approach: `{:style :rod}`.  It is presently experimental, which means that if you want me to change it I can.

Here are some examples:
```
zprint.core=> (czprint rod1 {:parse-string? true :style :rod})
(defn rod1
  "An exmple showing how pairs are indented."
  [a b c d]
  (cond (nil? a) (list d)
        (nil? b) (list c d a b)
        :else (list a b c d)))
nil
zprint.core=> (czprint rod2 {:parse-string? true :style :rod})
(defn rod2 [a b c d]
  (cond (nil? a) (list d)
        (nil? b) (list c d a b)
        :else (list a b c d)))
nil
zprint.core=> (czprint rod3 {:parse-string? true :style :rod})
(defn rod3
  ([a b c d]
   (cond (nil? a) (list d)
         (nil? b) (list c d a b)
         :else (list a b c d)))

  ([a b c]
   (rod3 a b c nil)))
nil
zprint.core=> (czprint rod4 {:parse-string? true :style :rod})
(defn rod4
  "A multi-arity test."
  ([a b c d]
   (cond (nil? a) (list d)
         (nil? b) (list c d a b)
         :else (list a b c d)))

  ([a b c]
   (rod4 a b c nil)))
nil
zprint.core=> (czprint rod5 {:parse-string? true :style :rod})
(defn rod5
  ([a b c d]
   (cond (nil? a) (list d)
         (nil? b) (list c d a b)
         :else (list a b c d)))

  ([a b c]
   (rod5 a b c nil))

  ([a b]
   (rod5 a b nil nil)))
nil
zprint.core=> (czprint rod6 {:parse-string? true :style :rod})
(defn rod6
  "Thus illustrating the rules of defn."
  ([a b c d]
   (cond (nil? a) (list d)
         (nil? b) (list c d a b)
         :else (list a b c d)))

  ([a b c]
   (rod6 a b c nil))

  ([a b]
   (rod6 a b nil nil)))
nil
zprint.core=> (czprint rod7 {:parse-string? true :style :rod})
(defn rod7
  "Thus illustrating the rules of defn."
  ([a b c d]
   (cond (nil? a) (list d)
         (nil? b) (list c d a b)
         :else (list a b c d)))

  ; This is a comment
  ; actually, a two line one
  ([a b c]  ; this is an embedded comment
   (rod7 a b c nil))

  ([a b]
   (rod7 a b nil nil)))
nil
```
I hope that this does what you want it to.  I encourage you to try it out and let me know if you think that there is anything that you would like me to change, or if it doesn't work in some way.  I have tested it rather extensively, but so far only on small examples.

**Comment by vemv** [comment]
> :rod

😄

wow, that sounds fantastic! I'll make sure to try it out. 

Also sorry for the lack of reply for the previous comment, I actually wanted to.

This is still very much a problem I care about.

**Comment by vemv** [comment]
> One thing that would help me a lot to understand your preferred formatting would be if you could point me at a repo (or even few files in a repo) that was formatted the way that you would like zprint to be able to format. 

Will try in a while, the ideal corpus would be diverse (defrecord, defprotocol, etc) and representative (only formatted by me, without e.g. formattings from people with other preferences)

> Here are some examples:

They all look perfect to me. Personally I tend to always place a newline after `cond` (so that it gets a 2-space indentation and it's super clear that it's a macro call and not a defn call). Probably it's unrelated to :rod though?

I guess that one could overwrite the cond rule without affecting :rod

**Comment by kkinnear** [comment]
The formatting for `cond` is, indeed, completely independent of the new `{:style :rod}`.  The "rules of defn" style only affects the formatting of the top level of the expression starting with `defn` and, if there is no vector of arguments (implying that it is multi-arity), then the formatting of expressions one level down that start with vectors.

If you want `cond` to be formatted differently, I can see what I can do if you give me an example.  It would be nice if that were a new issue, so I can track it effectively.

**Comment by kkinnear** [comment]
If you always want a newline after `cond`, you can get it this way:
```
zprint.core=> i170cond
"(defn rod8\n  \"Thus illustrating the rules of defn.\"\n  [a b c d]\n  (cond (nil? a) (list d)\n        (nil? b) (list c d a b)\n        (:require (more (and even more) stuff)) (what gives?)\n        :else (list a b c d)))\n"
zprint.core=> (czprint i170cond {:parse-string? true :fn-map {"cond" [:pair-fn {:pair-fn {:hang? false} :next-inner :restore}]}})
(defn rod8
  "Thus illustrating the rules of defn."
  [a b c d]
  (cond
    (nil? a) (list d)
    (nil? b) (list c d a b)
    (:require (more (and even more) stuff)) (what gives?)
    :else (list a b c d)))
```
Just use this options map:
```
{:fn-map {"cond" [:pair-fn {:pair-fn {:hang? false}, :next-inner :restore}]}}
```
I think this will give you want you want for `cond`.

**Comment by raymcdermott** [comment]
This is a great style. 

How easy is it make the extra newline optional? For example this:

```
(defn x 
  ([a]
   (x a 0))
  ([a b]
   (+ a b)))
```
rather than this:

```
(defn x 
  ([a]
   (x a 0))

  ([a b]
   (+ a b)))
```

**Comment by kkinnear** [comment]
This particular style is, well, very particular.  It would not be hard for me to make that extra line configurable, though it isn't now.   I'll work on getting that into the next release.  If it would be helpful, I could probably give you a function to put into your `.zprintrc` that would do what you want before the release comes out, so let me know if that is interesting.

**Comment by kkinnear** [comment]
I have enhanced the "rod" style to be configurable and include either one and two newlines between rarities.  This will appear in the next release, probably called `1.2.1`, sometime in the next month or two.  If you would like a version of this as a 30 line addition you could put in your `.zprintrc` file, let me know.

**Comment by vemv** [comment]
Looks like my original request has been implemented, and even supports tweaks!

Thank you for all the work.

**Comment by kkinnear** [comment]
Yes, I did the initial version back in May of 2021.  If you look back at the comment from that time, there are some examples of what it does.  If you have a chance, let me know if this is, indeed, what you were looking for.  It is still experimental, and so I can change it as necessary to conform to what you want if I have mis-interpreted your ideas in some way.

**Comment by vemv** [comment]
My overall impression is that they look good, and also I can observe that zprint supports a variety of styles and sub-styles now, so any further tweaks should be accomplishable with config as hinted here https://github.com/kkinnear/zprint/issues/170#issuecomment-1011261516

Sorry I couldn't leave as much feedback as I wanted, normally I always have some other OSS task in my head!

But with these new features I can think of zprint as a viable alternative for cljfmt in various places (cider-nrepl most notably).

Cheers - V

**Comment by kkinnear** [comment]
Thanks!

**Comment by kkinnear** [comment]
@raymcdermott, I released the enhancement you requested for style `:rod` in  zprint`1.2.1`, just out.  The style you want is called `:rod-no-ma-nl`, which means "Rules of Defn no multi-airity newlines".
