### ISSUE TITLE
inline zprint directives

### ISSUE THREAD

**Issue by lucywang000** [kkinnear/zprint#180]
Some lint/formatting tools accept inline directives / configuration that comes right before the code, 

e.g.:

clj-kondo:

```clojure
#_{:clj-kondo/ignore [:unresolved-symbol]}
(+ foo bar)
```
python yapf formatter:
```python
x = [
"first",
1, 2
3, 4
]  # yapf: disable
```

The use case is, most of the time I'd like to format bindings as pairs but sometimes I'd like it to format as flow and insert blank lines between each binding, esp. when there are lambdas that spans several lines. 

Could zprint support something like this:

```clojure
; zprint: {flow?: true :nl-separator? true}
; or 
#_{:zprint {:flow? true :nl-separator? true}}
(let [some-var
      some-value
        
      some-fn
      (fn []
           ....)]
  ... )
```

 Using comments is slightly better than using clojure ignore (`#_`) reader macro because in a editor the former is colored as comments so less distracting.

**Comment by kkinnear** [comment]
Easily done!  There is a "file comment API" which does exactly what you want -- you can see the cljdoc [here](https://cljdoc.org/d/zprint/zprint/1.1.1/doc/file-comment-api).   This interprets `;!zprint {...}` as a zprint options map, with some special controls which indicate how much of the associated file is affected by the options map.

Probably I should add this to the "I want to change..." section of the docs.  

Thanks for the suggestion!

**Comment by lucywang000** [comment]
Cool! Yeah this should be better linked in a obvious location.
