### ISSUE TITLE
Defprotocol with metadata indentation

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#181]
Hi Kim, I have the following issue I need some guidance on how to handle. Basically this:

```
(defprotocol ReportRepository
  "Store and retrieve."
  :extend-via-metadata true
  (add-report [repository report]
   "Add a report to the repository."))
```

is transformed into this:

```
(defprotocol ReportRepository
 "Store and retrieve."
   :extend-via-metadata
   true
   (add-report [repository report] "Add a report to the repository."))
```

The problems (imho):

* The comment is one indented one space - while cider/community does 2 there
* `:extend-via-metadata true` is not on the same line
* As a bonus request, would there be a way to have the comment on a separate line from the definition + args? I find it cleaner

My current configuration is

```
{:width  120
 :map    {:comma? false}
 :style  [:respect-bl
          :community
          :how-to-ns
          :binding-nl]
 :comment {:inline-align-style :none}
 :fn-map {"defhandler"  :fn
          ...
              "defprotocol" :arg1-extend}}
```

But I would put a question mark on `"defprotocol"` cause I would like to ask what is the best option there.

**Comment by kkinnear** [comment]
Hey @arichiardi, nice to hear from you!

You have brought up several issues here, which I appreciate! 
1. The indentation of `defprotocol` when using `:style :community`, which echos issue #176, which I have fixed and will be released with `1.1.2`, coming soon, I hope.
2. A new problem -- the `:extend-via-metadata true` that I missed in Clojure `1.10`, and which will need source changes to fix.  I will try hard to get them into `1.1.2` as well.
3. You would like any docstrings of the methods in a `defprotocol` to be on a separate line, which you can configure now (see below).

I can give you an options map which will solve #1 and #3, above, but I can't do anything about #2 without a source change.  Once `1.1.2` comes out, you won't need the fix for #1, but you will continue to need the options map to give you the behavior you want for #3.

Here is the best I can do for you today:

```clojure
(print i181d)
(defprotocol ReportRepository
  "Store and retrieve."
  :extend-via-metadata true
  (add-report [repository report]
   "Add a report to the repository."))

(czprint i181d
         {:parse-string? true,
          :fn-map {"defprotocol" [:arg1-force-nl
                                  {:fn-map {:default-not-none :arg1-force-nl},
                                   :list {:indent-arg 2, :constant-pair? false},
                                   :next-inner {:list {:indent-arg 1}}}]},
          :style :community})

(defprotocol ReportRepository
  "Store and retrieve."
  :extend-via-metadata
  true
  (add-report [repository report]
   "Add a report to the repository."))
```
After `1.1.2` comes out, this is what you will do, only to get the docstrings on the next line:
```clojure
(czprint i181d
         {:parse-string? true,
          :fn-map {"defprotocol" [:arg1-force-nl-body
                                  {:fn-map
                                    {:default-not-none :arg1-force-nl}}]}
          :style :community})
```
This won't work today because there isn't a valid fn-type of `:arg1-force-nl-body`, and in fact that may not be what you will need to use anyway, as I may have to create an additional new fn-type for `defprotocol` given that I have to handle the `:extend-via-metadata true`, which is new.  We will have to see once I dive into the implementation of this.

Thanks again for bringing up these issues!

**Comment by arichiardi** [comment]
@kkinnear this is awesome!

I am going to try it right away and report back.

**Comment by arichiardi** [comment]
@kkinnear I got an error with the former fix:

```
[:fn-map "defprotocol"] -> [:arg1-force-nl-body {:fn-map {:default-not-none :arg1-force-nl}}] was not recognized as valid!
```

Digging into it

**Comment by kkinnear** [comment]
Maybe I wasn't clear -- the second one I gave you doesn't work yet.  This is the one that works now:
```clojure
(czprint i181d
         {:parse-string? true,
          :fn-map {"defprotocol" [:arg1-force-nl
                                  {:fn-map {:default-not-none :arg1-force-nl},
                                   :list {:indent-arg 2, :constant-pair? false},
                                   :next-inner {:list {:indent-arg 1}}}]},
          :style :community})
```

**Comment by arichiardi** [comment]
No well you were clear Kim, it's just early morning here and I have copied the wrong snippet :coffee: 

Thank you!

**Comment by arichiardi** [comment]
Sorry, for some reason I get this now:

```
 [:fn-map "defprotocol"] -> [:arg1-force-nl {:next-inner {:list {:indent-arg 1}}, :list {:indent-arg 2, :constant-pair? false}, :fn-map {:default-not-none :arg1-force-nl}}] was not recognized as valid! because the value of the key-sequence [0] -> :default-not-none was not a clojure.core/string?
```

`zprint-1.1.1`

**Comment by kkinnear** [comment]
Sorry about that, try `:default` instead of `:default-not-none`.  I had fixed a bug that I didn't remember fixing a couple of months ago.  Hopefully that will work instead.

**Comment by arichiardi** [comment]
Works perfectly thank you! I think I am good for now until `1.1.2` is out - I have also learned how to go nested from your example - so thanks a lot.

Do you want me to open an issue with `#2`? 

Cause it might go hand-in-hand with managing the new way of *implementing* with meta...

I am using this style now:

``` clojure
  (with-meta
    {:db db}
    {`repository/all  (fn [_] (throw (UnsupportedOperationException.)))
     `repository/one  find-by-id
     `repository/some find-by-criteria

    })
```

I have seen inlined functions in the wild as well though, so that's a tricky one :smile: 

Closing this!

**Comment by kkinnear** [comment]
No, let's leave this issue open and I'll use it to track #2, above.

Regarding `with-meta`, this is what you get today.  Is this not what you would want?

```clojure
(czprint i181e {:parse-string? true})
(with-meta {:db db}
  {`repository/all (fn [_] (throw (UnsupportedOperationException.))),
   `repository/one find-by-id,
   `repository/some find-by-criteria})
```
If that is not what you want, please show me what you would want.  Thanks!

**Comment by arichiardi** [comment]
Hey Kim, thanks for asking, well `{:db db}` usually gets big and so it is better to have it on a separate line. I guess thought that would be a simple `:noarg1-body`? Did not check the manual yet for that one :smile:

**Comment by kkinnear** [comment]
Ok, I could see maybe `:none-body`, or `:flow-body` maybe.  `:noarg1-body` is kind of specialized for `->` and friends, so I'm not sure that would be the best thing.  

If you have a realistic `with-meta` expression that has more information in it, I would love to see it and be able to use it to try things out and put into the tests.  It doesn't have to make sense, I'll not be executing it, just formatting the string.  Big would be fine, that way I know what to expect.  

This metadata definition is all new to me, so since you are clearly doing it, I'd love to see a substantial `with-meta` (and while you are at it, a substantial `defprotocol` if you have one bigger than the one you sent me already).  Thanks!

**Comment by arichiardi** [comment]
Yeah I can do that, I wrote you on Slack / if you have an PGP key or more private method to reach you I can definitely send you some example.

**Comment by kkinnear** [comment]
I don't do Slack much at all.  I get enough interruptions during the limited time I have to code.  If sending me code in email isn't secure enough, I probably shouldn't have it.  Thanks anyway, and sorry to bother you about it.

**Comment by arichiardi** [comment]
Ah no bother at all, you can definitely have it I just don't want paste it on github 😃 Will use the email 😉

**Comment by kkinnear** [comment]
The metadata information is now handled correctly:
```
zprint.core=> (print i181)
(defprotocol ReportRepository
  "Store and retrieve."
  :extend-via-metadata true
  (add-report [repository report]
   "Add a report to the repository."))
nil
zprint.core=> (czprint i181 {:parse-string? true})
(defprotocol ReportRepository
  "Store and retrieve."
  :extend-via-metadata true
  (add-report [repository report] "Add a report to the repository."))
```
Thanks for pointing this out, I had missed it.

In addition, you wanted the docstrings handled differently.  Here is a way to do that:
```
zprint.core=> (print i181a)
(defprotocol AProtocolName
  "A doc string for AProtocol abstraction"
  :extend-via-metadata true
  (bar [this a b]
    "bar docs")
  (baz [this a]
       [this a b]
       [this a b c]
    "baz docs"))
nil

; The default way

zprint.core=> (czprint i181a {:parse-string? true})
(defprotocol AProtocolName
  "A doc string for AProtocol abstraction"
  :extend-via-metadata true
  (bar [this a b] "bar docs")
  (baz [this a] [this a b] [this a b c] "baz docs"))
nil

; A way that I think you wanted it

zprint.core=> (czprint i181a {:parse-string? true :fn-map {"defprotocol" [:none-body {:style :defprotocolguide :fn-map {:default-not-none [:none {:style :signature1}]}}]}})
(defprotocol AProtocolName
  "A doc string for AProtocol abstraction"
  :extend-via-metadata true
  (bar [this a b]
    "bar docs")
  (baz [this a]
       [this a b]
       [this a b c]
    "baz docs"))
```
I haven't released `:style :signature1` for general use, so if you want it different, let me know.

**Comment by arichiardi** [comment]
Thank you Kim, yes the latter with function comments below arities is way more readable in my opinion and worth releasing 😃

**Comment by arichiardi** [comment]
Hi @kkinnear 
so this is what I ended up using for now:

```clojure
          "defprotocol" [:arg1-force-nl
                         {:style :defprotocolguide
                          :fn-map {:default :flow}
                          :list {:indent-arg 2
                                 :constant-pair? false}
                          :next-inner {:list {:indent-arg 1}}}]
```

I am quite happy with it, see two examples below:

```clojure
(defprotocol Repository
  :extend-via-metadata true
  (-all
   [repository]
   "Fetch all items from the repository.")
  (-one
   [repository id]
   "Fetch a particular item, identified by `id`, from the repository.")
  (-some
   [repository specification]
   "Fetch items from the repository matching `specification`."))

;; TODO better spec - note that use satisfies? with the metadata cannot be used
;;
;; https://ask.clojure.org/index.php/4622/satisfies-doesnt-work-instance-based-protocol-polymorphism
(s/def ::repository any?)

(defprotocol AProtocolName
  "A doc string for AProtocol abstraction"
  :extend-via-metadata true
  (bar
   [this a b]
   "bar docs")
  (baz
   [this a]
   [this a b]
   [this a b c]
   "baz docs"))
```

**Comment by kkinnear** [comment]
This should work out of the box with `1.2.0`.
