### ISSUE TITLE
Community style indents comment form in not useful form

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#182]
Hi there, I am maybe going to take care of this cause it seems simple enough but I have noticed that the `:community` style formats my `(comment ...)` forms from this way:

```clojure
(comment
  (require '[clojure.java.io :as io] 'dev)
  (import 'org.apache.commons.io.IOUtils))
```

to this:
```clojure
(comment (require '[clojure.java.io :as io] 'dev)
         (import 'org.apache.commons.io.IOUtils))
```

I am not sure about others but I find the former more common in all the code bases I have seen (plus my current one).

The fix is easy but I was thinking of bringing this up to see what others think about modifying `:community`.

**Comment by kkinnear** [comment]
Thanks for bringing this up!

I would have no problem giving `comment` a fn-type (which it doesn't have at the moment).  Seems like `:flow-body` would be the correct one.  If someone didn't like that they could put it back to `:none`. 

Here is the default approach.  (I sure hope that your second line was a cut-and-paste artifact, and not something zprint actually output.)
```clojure
(print i182)
(comment
  (require '[clojure.java.io :as io] 'dev)
  (import 'org.apache.commons.io.IOUtils))

(czprint i182 {:parse-string? true :style :community})
(comment (require '[clojure.java.io :as io] 'dev)
         (import 'org.apache.commons.io.IOUtils))
```
Here is what I would propose -- `:flow-body` for `comment`:
```clojure
(czprint i182 {:parse-string? true :style :community :fn-map {"comment" :flow-body}})
(comment
  (require '[clojure.java.io :as io] 'dev)
  (import 'org.apache.commons.io.IOUtils))
```
 I've helped several people get their comment functions to not remove new-lines at the top level, so when they commented out a lot of stuff, it wouldn't look all that different.  But that is only really interesting for when the `comment` function is at the top level.  I can imagine a simple bit of code that would format the comment function differently if it is at the top level then if it is not at the top level.  But that might be more complex than people want to get.

Anyway, I'm open to more suggestions here.

**Comment by arichiardi** [comment]
Yeah `:flow body` is what I have used, I agree and imho it should be the default.

**Comment by kkinnear** [comment]
This is now fixed in `1.1.2`:
```
zprint.core=> (print i182)
(comment
  (require '[clojure.java.io :as io] 'dev)
  (import 'org.apache.commons.io.IOUtils))
nil
zprint.core=> (czprint i182 {:parse-string? true})
(comment
  (require '[clojure.java.io :as io] 'dev)
  (import 'org.apache.commons.io.IOUtils))
```
Thanks for pointing it out!

**Comment by arichiardi** [comment]
Thank you!

**Comment by arichiardi** [comment]
Can confirm this works:

```diff   ;; in case want to use the REPL instead of the fixture execution
   ;; the following sets test/*test-system*
   (def system (test/start-test-system! [sut-system-key]))
-
   (require '[com.cohesic.acuity.test.setup :as setup])
   (setup/run-drop-script! {})
-  (setup/run-setup-script! {})
-)
+  (setup/run-setup-script! {}))
```

I don't have any option set for this - thank you for the fix again, closing.
