### ISSUE TITLE
Sort deps.edn dependencies

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#183]
Hi there again Kim :smile: 

This time I am trying to sort the `:deps` key of the following:

```clojure
;;!zprint {:map {:justify? true :force-nl? true :sort? true}}
{:paths ["dev" "src" "resources"]
 :deps {buddy/buddy-hashers                 {:mvn/version "1.3.0"}
        ca.uhn.hapi/hapi-base               {:mvn/version "2.3"}
        camel-snake-kebab/camel-snake-kebab {:mvn/version "0.4.0"}
        ch.qos.logback/logback-classic      {:mvn/version "1.2.3"}
        buddy/buddy-sign                    {:mvn/version "2.2.0"}
        clj-commons/iapetos                 {:mvn/version "0.1.9"}
        com.bhauman/spell-spec              {:mvn/version "0.1.1"}
        com.layerware/hugsql                {:mvn/version "0.5.1"}
        com.rpl/specter                     {:mvn/version "1.1.1"}
        com.taoensso/tufte                  {:mvn/version "2.0.1"}
        duct/core                           {:mvn/version "0.6.2"}
        duct/database.sql.hikaricp          {:mvn/version "0.3.3"}
        expound/expound                     {:mvn/version "0.7.2"}
        http-kit/http-kit                   {:mvn/version "2.2.0"}
        io.pedestal/pedestal.jetty          {:mvn/version "0.5.3"}
        io.pedestal/pedestal.route          {:mvn/version "0.5.3"}
        io.pedestal/pedestal.service        {:mvn/version "0.5.3"}
        io.prometheus/simpleclient_hotspot  {:mvn/version "0.9.0"}
        me.raynes/conch                     {:mvn/version "0.8.0"}
        metosin/muuntaja                    {:mvn/version "0.6.0"}
        metosin/ring-http-response          {:mvn/version "0.9.0"}
        mysql/mysql-connector-java          {:mvn/version "8.0.19"}
        org.apache.poi/poi-ooxml            {:mvn/version "4.1.0"}
        org.clojure/clojure                 {:mvn/version "1.10.1"}
        org.clojure/core.cache              {:mvn/version "0.8.2"}
        org.clojure/core.match              {:mvn/version "0.3.0-alpha5"}
        org.clojure/core.memoize            {:mvn/version "0.8.2"}
        org.clojure/java.jdbc               {:mvn/version "0.7.12"}
        org.clojure/tools.cli               {:mvn/version "0.4.2"}
        org.clojure/tools.logging           {:mvn/version "0.6.0"}
        org.clojure/tools.reader            {:mvn/version "1.3.4"}
        org.postgresql/postgresql           {:mvn/version "42.2.2"}
        org.slf4j/jcl-over-slf4j            {:mvn/version "1.7.30"}
        org.slf4j/jul-to-slf4j              {:mvn/version "1.7.30"}
        org.slf4j/log4j-over-slf4j          {:mvn/version "1.7.30"}
        ring/ring-core                      {:mvn/version "1.6.3"}}}
```

However `:sort? true` does not seem to apply? I also would not want to change the order of the top level keys, only of the ones inside `:deps`.

Is there a way to achieve that?

**Comment by kkinnear** [comment]
Andrea,

There is no way to apply an options map to just one key, but that is an interesting idea.

You *can* say which keys should come first and what order they should be in, which if you have only a few maps, or only a few different “types” of maps, might give you what you want.  

I don’t have any idea why sorting is not working for you.  You might want to send me a configuration and an example where sorting didn’t work (as when I tried sorting, it works fine).

Here is what I did:

This is not sorted:

(print iar3)
{:paths ["dev" "src" "resources"]
 :deps {buddy/buddy-hashers                 {:mvn/version "1.3.0"}
        ca.uhn.hapi/hapi-base               {:mvn/version "2.3"}
        camel-snake-kebab/camel-snake-kebab {:mvn/version "0.4.0"}
        io.pedestal/pedestal.route          {:mvn/version "0.5.3"}
        io.pedestal/pedestal.service        {:mvn/version "0.5.3"}
        io.prometheus/simpleclient_hotspot  {:mvn/version "0.9.0"}
        me.raynes/conch                     {:mvn/version "0.8.0"}
        metosin/muuntaja                    {:mvn/version "0.6.0"}
        metosin/ring-http-response          {:mvn/version "0.9.0"}
        mysql/mysql-connector-java          {:mvn/version "8.0.19"}
        org.apache.poi/poi-ooxml            {:mvn/version "4.1.0"}
        org.clojure/clojure                 {:mvn/version "1.10.1"}
        org.clojure/core.cache              {:mvn/version "0.8.2"}
        org.clojure/core.match              {:mvn/version "0.3.0-alpha5"}
        org.clojure/core.memoize            {:mvn/version "0.8.2"}
        org.clojure/java.jdbc               {:mvn/version "0.7.12"}
        org.clojure/tools.cli               {:mvn/version "0.4.2"}
        org.clojure/tools.logging           {:mvn/version "0.6.0"}
        ch.qos.logback/logback-classic      {:mvn/version "1.2.3"}
        buddy/buddy-sign                    {:mvn/version "2.2.0"}
        clj-commons/iapetos                 {:mvn/version "0.1.9"}
        com.bhauman/spell-spec              {:mvn/version "0.1.1"}
        com.layerware/hugsql                {:mvn/version "0.5.1"}
        com.rpl/specter                     {:mvn/version "1.1.1"}
        com.taoensso/tufte                  {:mvn/version "2.0.1"}
        duct/core                           {:mvn/version "0.6.2"}
        duct/database.sql.hikaricp          {:mvn/version "0.3.3"}
        expound/expound                     {:mvn/version "0.7.2"}
        http-kit/http-kit                   {:mvn/version "2.2.0"}
        io.pedestal/pedestal.jetty          {:mvn/version "0.5.3"}
        org.clojure/tools.reader            {:mvn/version "1.3.4"}
        org.postgresql/postgresql           {:mvn/version "42.2.2"}
        org.slf4j/jcl-over-slf4j            {:mvn/version "1.7.30"}
        org.slf4j/jul-to-slf4j              {:mvn/version "1.7.30"}
        org.slf4j/log4j-over-slf4j          {:mvn/version "1.7.30"}
        ring/ring-core                      {:mvn/version "1.6.3"}}}
nil

Here is where I told :map what key-order to use, so that this puts :paths first, all the time.

zprint.core=> (czprint iar3 {:parse-string? true :map {:key-order [:paths] :justify? true}})

{:paths ["dev" "src" "resources"],
 :deps  {buddy/buddy-hashers                 {:mvn/version "1.3.0"},
         buddy/buddy-sign                    {:mvn/version "2.2.0"},
         ca.uhn.hapi/hapi-base               {:mvn/version "2.3"},
         camel-snake-kebab/camel-snake-kebab {:mvn/version "0.4.0"},
         ch.qos.logback/logback-classic      {:mvn/version "1.2.3"},
         clj-commons/iapetos                 {:mvn/version "0.1.9"},
         com.bhauman/spell-spec              {:mvn/version "0.1.1"},
         com.layerware/hugsql                {:mvn/version "0.5.1"},
         com.rpl/specter                     {:mvn/version "1.1.1"},
         com.taoensso/tufte                  {:mvn/version "2.0.1"},
         duct/core                           {:mvn/version "0.6.2"},
         duct/database.sql.hikaricp          {:mvn/version "0.3.3"},
         expound/expound                     {:mvn/version "0.7.2"},
         http-kit/http-kit                   {:mvn/version "2.2.0"},
         io.pedestal/pedestal.jetty          {:mvn/version "0.5.3"},
         io.pedestal/pedestal.route          {:mvn/version "0.5.3"},
         io.pedestal/pedestal.service        {:mvn/version "0.5.3"},
         io.prometheus/simpleclient_hotspot  {:mvn/version "0.9.0"},
         me.raynes/conch                     {:mvn/version "0.8.0"},
         metosin/muuntaja                    {:mvn/version "0.6.0"},
         metosin/ring-http-response          {:mvn/version "0.9.0"},
         mysql/mysql-connector-java          {:mvn/version "8.0.19"},
         org.apache.poi/poi-ooxml            {:mvn/version "4.1.0"},
         org.clojure/clojure                 {:mvn/version "1.10.1"},
         org.clojure/core.cache              {:mvn/version "0.8.2"},
         org.clojure/core.match              {:mvn/version "0.3.0-alpha5"},
         org.clojure/core.memoize            {:mvn/version "0.8.2"},
         org.clojure/java.jdbc               {:mvn/version "0.7.12"},
         org.clojure/tools.cli               {:mvn/version "0.4.2"},
         org.clojure/tools.logging           {:mvn/version "0.6.0"},
         org.clojure/tools.reader            {:mvn/version "1.3.4"},
         org.postgresql/postgresql           {:mvn/version "42.2.2"},
         org.slf4j/jcl-over-slf4j            {:mvn/version "1.7.30"},
         org.slf4j/jul-to-slf4j              {:mvn/version "1.7.30"},
         org.slf4j/log4j-over-slf4j          {:mvn/version "1.7.30"},
         ring/ring-core                      {:mvn/version "1.6.3"}}}

It came out sorted.

Let me know if the sorting really doesn’t work.

Cheers — Kim

**Comment by kkinnear** [comment]
Actually, it would be very straightforward to have a map option: key-value-options, which would be a map of keys and options maps to use when formatting the values.  I already have key-value-color, which is similar in concept.

Thanks for the idea!

Cheers — Kim

**Comment by arichiardi** [comment]
@kkinnear yep the idea of having something to tell that I want exactly `:deps` keys sorted rather then all is very nice indeed.

I have tried the above file with the following configuration in `~/.zprint.edn`

```
{:width 100
 :style [:respect-bl
         :community
         :how-to-ns
         :binding-nl]
 :map {:comma? false}
 :comment {:inline-align-style :none}}
```

and `zprint -slw my-deps.edn` basically spits "Processed 1 file, none of which required formatting".

**Comment by arichiardi** [comment]
I see this with `--explain` for map:

```
:map
 {:indent      {:set-by "Home directory file: /home/cokap/.zprint.edn specified :style :community"
                :value  0}
  :comma?      {:set-by "Home directory file: /home/cokap/.zprint.edn"
                :value  false}
  :justify?    {:set-by "Home directory file: /home/cokap/.zprint.edn"
                :value  true}
  :force-nl?   {:set-by "Home directory file: /home/cokap/.zprint.edn"
                :value  true}
  :key-order   {:set-by "Home directory file: /home/cokap/.zprint.edn"
                :value  [:paths]}
  :respect-bl? {:set-by "Home directory file: /home/cokap/.zprint.edn specified :style :respect-bl"
                :value  true}
  :sort?       {:set-by "Home directory file: /home/cokap/.zprint.edn"
                :value  true}}}
```

I am scratching my head now cause I don't understand why it is not doing it in my case :smile:

**Comment by kkinnear** [comment]
Oh, right.  I had to try it before I remembered what is going on.  If you have :respect-bl? or :respect-nl? as true for :map it disables sorting.  The idea being: if I move things around for the sorting, how would I know where the newlines should go?

So, here is my example:

First, with your map configuration — it doesn’t sort:

(czprint iar3 {:parse-string? true :map {:comma? false, :force-nl? true, :indent 0, :justify? true, :key-order [:paths], :respect-bl? true, :sort? true}})
{:paths ["dev" "src" "resources"]
 :deps  {buddy/buddy-hashers                 {:mvn/version "1.3.0"}
         ca.uhn.hapi/hapi-base               {:mvn/version "2.3"}
         camel-snake-kebab/camel-snake-kebab {:mvn/version "0.4.0"}
         io.pedestal/pedestal.route          {:mvn/version "0.5.3"}
         io.pedestal/pedestal.service        {:mvn/version "0.5.3"}
         io.prometheus/simpleclient_hotspot  {:mvn/version "0.9.0"}
         me.raynes/conch                     {:mvn/version "0.8.0"}
         metosin/muuntaja                    {:mvn/version "0.6.0"}
         metosin/ring-http-response          {:mvn/version "0.9.0"}
         mysql/mysql-connector-java          {:mvn/version "8.0.19"}
         org.apache.poi/poi-ooxml            {:mvn/version "4.1.0"}
         org.clojure/clojure                 {:mvn/version "1.10.1"}
         org.clojure/core.cache              {:mvn/version "0.8.2"}
         org.clojure/core.match              {:mvn/version "0.3.0-alpha5"}
         org.clojure/core.memoize            {:mvn/version "0.8.2"}
         org.clojure/java.jdbc               {:mvn/version "0.7.12"}
         org.clojure/tools.cli               {:mvn/version "0.4.2"}
         org.clojure/tools.logging           {:mvn/version "0.6.0"}
         ch.qos.logback/logback-classic      {:mvn/version "1.2.3"}
         buddy/buddy-sign                    {:mvn/version "2.2.0"}
         clj-commons/iapetos                 {:mvn/version "0.1.9"}
         com.bhauman/spell-spec              {:mvn/version "0.1.1"}
         com.layerware/hugsql                {:mvn/version "0.5.1"}
         com.rpl/specter                     {:mvn/version "1.1.1"}
         com.taoensso/tufte                  {:mvn/version "2.0.1"}
         duct/core                           {:mvn/version "0.6.2"}
         duct/database.sql.hikaricp          {:mvn/version "0.3.3"}
         expound/expound                     {:mvn/version "0.7.2"}
         http-kit/http-kit                   {:mvn/version "2.2.0"}
         io.pedestal/pedestal.jetty          {:mvn/version "0.5.3"}
         org.clojure/tools.reader            {:mvn/version "1.3.4"}
         org.postgresql/postgresql           {:mvn/version "42.2.2"}
         org.slf4j/jcl-over-slf4j            {:mvn/version "1.7.30"}
         org.slf4j/jul-to-slf4j              {:mvn/version "1.7.30"}
         org.slf4j/log4j-over-slf4j          {:mvn/version "1.7.30"}
         ring/ring-core                      {:mvn/version "1.6.3"}}}

Then, with :respect-bl? false, it will sort:

(czprint iar3 {:parse-string? true :map {:comma? false, :force-nl? true, :indent 0, :justify? true, :key-order [:paths], :respect-bl? false, :sort? true}})
{:paths ["dev" "src" "resources"]
 :deps  {buddy/buddy-hashers                 {:mvn/version "1.3.0"}
         buddy/buddy-sign                    {:mvn/version "2.2.0"}
         ca.uhn.hapi/hapi-base               {:mvn/version "2.3"}
         camel-snake-kebab/camel-snake-kebab {:mvn/version "0.4.0"}
         ch.qos.logback/logback-classic      {:mvn/version "1.2.3"}
         clj-commons/iapetos                 {:mvn/version "0.1.9"}
         com.bhauman/spell-spec              {:mvn/version "0.1.1"}
         com.layerware/hugsql                {:mvn/version "0.5.1"}
         com.rpl/specter                     {:mvn/version "1.1.1"}
         com.taoensso/tufte                  {:mvn/version "2.0.1"}
         duct/core                           {:mvn/version "0.6.2"}
         duct/database.sql.hikaricp          {:mvn/version "0.3.3"}
         expound/expound                     {:mvn/version "0.7.2"}
         http-kit/http-kit                   {:mvn/version "2.2.0"}
         io.pedestal/pedestal.jetty          {:mvn/version "0.5.3"}
         io.pedestal/pedestal.route          {:mvn/version "0.5.3"}
         io.pedestal/pedestal.service        {:mvn/version "0.5.3"}
         io.prometheus/simpleclient_hotspot  {:mvn/version "0.9.0"}
         me.raynes/conch                     {:mvn/version "0.8.0"}
         metosin/muuntaja                    {:mvn/version "0.6.0"}
         metosin/ring-http-response          {:mvn/version "0.9.0"}
         mysql/mysql-connector-java          {:mvn/version "8.0.19"}
         org.apache.poi/poi-ooxml            {:mvn/version "4.1.0"}
         org.clojure/clojure                 {:mvn/version "1.10.1"}
         org.clojure/core.cache              {:mvn/version "0.8.2"}
         org.clojure/core.match              {:mvn/version "0.3.0-alpha5"}
         org.clojure/core.memoize            {:mvn/version "0.8.2"}
         org.clojure/java.jdbc               {:mvn/version "0.7.12"}
         org.clojure/tools.cli               {:mvn/version "0.4.2"}
         org.clojure/tools.logging           {:mvn/version "0.6.0"}
         org.clojure/tools.reader            {:mvn/version "1.3.4"}
         org.postgresql/postgresql           {:mvn/version "42.2.2"}
         org.slf4j/jcl-over-slf4j            {:mvn/version "1.7.30"}
         org.slf4j/jul-to-slf4j              {:mvn/version "1.7.30"}
         org.slf4j/log4j-over-slf4j          {:mvn/version "1.7.30"}
         ring/ring-core                      {:mvn/version "1.6.3"}}}

Just add {:map {:respect-bl? false} in your ;!zprint options map, and I think you will be ok.

Cheers — Kim

**Comment by arichiardi** [comment]
> If you have :respect-bl? or :respect-nl? as true for :map it disables sorting.  The idea being: if I move things around for the sorting, how would I know where the newlines should go?

Definitely makes sense!

**Comment by arichiardi** [comment]
Apologizing, overnight I was thinking:

If I have

```
{:d 4
 
 :c 3
 :b 2

 :a 1}
```

I would think zprint respects newlines if it outputted:

```
{:a 1
 
 :b 2
 :c 3

 :d 4}
```

But maybe I am missing something...

**Comment by kkinnear** [comment]
I certainly agree that *might* be what you wanted -- i.e., the newlines were to separate the first from the group of second and third, and that group from the last.  But what if you wanted the newlines *before* `:c` and `:a` in order to make them more visible?  Or what if you wanted the newlines to come *after* `:d` and `:b`?

Now, I could see for `:respect-bl?` checking the actual information, and if there were no blank lines and `:sort?` was true, going ahead and doing the sorting.  I think that would be safe enough.  Of course, if they then put in a blank line, the sorting would stop, which sort of violates the "least surprise" principle of user interface design.

Unfortunately that wouldn't work for `:respect-nl?`, because there are almost always newlines.  Of course, if there were no newlines that zprint wouldn't have put in anyway, then sorting would still be ok -- but determining that would be exceptionally difficult, since it would potentially be affected by the results of the sorting itself.  

I'll give this some more thought.

**Comment by arichiardi** [comment]
Oh I see there I might be talking about `respect-bl?` myself.

Thank you Kim, there could even be a :sorting-respect-bl? new style that does that. At least intention is clear and no surprises there.

**Comment by arichiardi** [comment]
Hi Kim this is working for me, closing it and thank you!
