### ISSUE TITLE
Force newline between :pre and :post

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#185]
Hi again @kkinnear and sorry for bombaring but my colleagues like the tool so we are going to have more and more questions coming :smile: 

This particular questions is around `:pre/:post` blocks. What we have is something like this:

```clojure
 (defn ->do-foo
   [x]
   {:pre [(map? m) (empty? m)]
    :post [(not-empty %)]}
   (println "foo"))
```

We would like to keep it like that, separate lines for both and clauses within the vectors on the same line where possible.

Is there a magic trick to target only that map without changing how the body of `defn` is treated?

**Comment by arichiardi** [comment]
What I am trying to do is 

```clojure
{:fn-map {"defn"
 [:arg1-body
       {:map {:force-nl? true
                  :sort? true
                  :key-order [:pre :post]}}]}
```

But that modifies all the maps in the `defn` body and I do not want to do that.

**Comment by kkinnear** [comment]
Today there is no way to do this.  I have a way that *should* work, but unfortunately I had to fix a bug to get it to work, as I've never tried to do this before.   This says that for maps one level down from the defn, use `:force-nl? true`, but then turn it off for maps any lower down.
```
(czprint
  i185
  {:parse-string? true,
   :fn-map {"defn" [:arg1-body
                    {:next-inner {:map {:force-nl? true},
                                  :next-inner {:map {:force-nl? false}}}}]}})
(defn ->do-foo
  [x]
  {:pre [(map? m) (empty? m)],
   :post [(not-empty %)]}
  (println "foo" {:this :is, :a :map}))
```
In `1.1.2`, under development, this will work -- but in `1.1.1` all of the maps in the defn will have their keys on separate lines.

I'm working hard to get `1.1.2` out, but it has a significant new capability that is taking a while to wring out completely.  This new capability would let me do what you want in a completely different way that would work as well.

**Comment by arichiardi** [comment]
@kkinnear no worries - that's good to know there is a fix coming and please let me know if you want me to try it out at some point, I was actually thinking about doing exactly the same:

```clojure
"defn"  [:arg1-body
                  {:map {:force-nl? true
                         :sort-in-code? false
                         :sort? true
                         :key-order [:pre :post]}
                   :next-inner {:map {:force-nl? false
                                      :sort? false}}}]
```

**Comment by arichiardi** [comment]
Just to confirm, would this bug you solve also affect this resetting in `:next-inner`?

```
          "as->" [:arg2
                  {:fn-map {:default :force-nl}
                   :next-inner {:default :arg2}}]
```

Basically I would like to avoid printing `as->` clauses on the same line.

**Comment by kkinnear** [comment]
The `:next-inner` bug is that (today) you can't have a `:next-inner` inside a map in a `:next-inner`.  You can't nest them.  

`:next-inner` isn't to solution to the `as->` issue.  What you want is to have `:arg2` be in the `:fn-force-nl` set, like this:
```
(def i185a "(as-> x (this is an expr)\n   (stuff to do)\n   (bother to do it))\n   \n")

(czprint i185a
         {:parse-string? true,
          :fn-map {"as->" [:arg2
                           {:fn-force-nl #{:arg2},
                            :next-inner {:remove {:fn-force-nl #{:arg2}}}}]}})

(as-> x (this is an expr)
  (stuff to do)
  (bother to do it))
```
The `:next-inner` here removes `:arg2` from the set `:fn-force-nl` so that it doesn't affect any `:arg2` functions lower down inside the `as->` body.  Not that there are that many `:arg2` functions around, actually, but it doesn't hurt to be sure.

**Comment by arichiardi** [comment]
Wow learning a new trick every day thank you!

**Comment by arichiardi** [comment]
Ok so I tried this

```clojure
[:arg1-body
                  {:next-inner {:map {:force-nl? true 
                                      :sort-in-code? false 
                                      :sort? true 
                                      :key-order [:pre :post]}
                                  :next-inner {:map {:force-nl? false}}}}]
```

And it looks good but also this happens:

```diff
 (defn make-report-type
   [type procedure-type label]
   {:post [(types/is? ::report-type %)]}
-  {::type type ::procedure-type procedure-type ::label label})
+  {::type type
+   ::procedure-type procedure-type
+   ::label label})
```

I am not sure it's what you intended so I am reporting it here :D

**Comment by kkinnear** [comment]
So the `{:map {:force-nl? true}}` is what gets you a newline between `:pre` and `:post`.  But it is also going to get you newlines between the pairs of any top-level maps.  Not maps down inside the code, just the ones at the top level of a `defn`.

 I can (now) write a special thing to just do `{:map {:force-nl? true}}` just for a map with `:pre` or `:post` in it.  Or at least I think I can.  I'll let you know how it comes out.  For now, you either get newlines between all top level maps, or none of them if they fit on one line.

**Comment by arichiardi** [comment]
Ok yeah I was suspecting something like that - `:pre/post` are part of the language and they probably deserve a special configuration for them so I would be definitely happy to have something like that.

**Comment by arichiardi** [comment]
Looking at the source code again today - the issue is actually quite a non-issue - top level maps looks odd if they fit on the same line and I quite like the fact that now always have a newline between entries.

**Comment by kkinnear** [comment]
Thanks for bringing this up.  The latest version of an options map which will do "nice" things for `:pre` and `:post` is this:
```
{:fn-map
   {"defn"
      [:arg1-body
       {:next-inner {:map {:force-nl? true,
                           :key-order [:pre :post],
                           :sort-in-code? true,
                           :sort? true},
                     :next-inner-restore [[:map :force-nl?] [:map :key-order]
                                          [:map :sort?]
                                          [:map :sort-in-code?]]}}]}}
```
This options map turns this:
```
(defn selected-protocol-for-indications
  {:post [(not-empty %)], :pre [(map? m) (empty? m)]}
  [{:keys [spec]} procedure-id indications]
  (->> {:procedure-id procedure-id, :indications indications}
       (sql/op spec queries :selected-protocol-for-indications)
       (map :protocol-id)))
```
into this:
```
(defn selected-protocol-for-indications
  {:pre [(map? m) (empty? m)],
   :post [(not-empty %)]}
  [{:keys [spec]} procedure-id indications]
  (->> {:procedure-id procedure-id, :indications indications}
       (sql/op spec queries :selected-protocol-for-indications)
       (map :protocol-id)))
```



I don't think that is what you are using, and that's fine, but I wanted to put it here in case someone else sees this issue and wants their `:pre` and `:post` to look nice.

Thanks again for bringing this up!
