### ISSUE TITLE
Linux Executable Not Working for Me

### ISSUE THREAD

**Issue by stelcodes** [kkinnear/zprint#195]
Hey! I really want to use zprint. I'm on a x86 Linux NixOS machine. I downloaded zprintl-1.1.2. I ran `chmod +x`. But when I run `./zprintl-1.1.2` I get `bash: ./zprintl-1.1.2: No such file or directory` which seems to be error one would get when they try to run a binary that's incompatible with their system. I have other binaries in the same directory with the same permissions that work fine. I'm pretty experienced with Linux but I have never come across this issue when installing binaries. I'm running the latest version of NixOS on a 2013 Intel Macbook Air. I would really appreciate any help! Thanks.

**Comment by stelcodes** [comment]
If anyone comes across this, this is a common issue with NixOS. The dynamically linked libraries the zprintl binary requires are not correctly linked. I made a derivation for zprint that produces a working binary and I hope to add it to nixpkgs soon!

**Comment by kkinnear** [comment]
Wow, I was just getting a docker image of NixOS and researching this to try to send you an answer.  Thanks for what you are doing to get zprint to work on NixOS!  In case anyone else sees this, here was the best information I found:

https://discourse.nixos.org/t/how-to-deal-with-lib64-ld-linux-x86-64-so-2-missing-on-nixos/11401

with this looking promising:

https://github.com/Mic92/nix-ld

Thanks again for bringing this up!  I'm going to change the title so it will more obvious to people looking at issues.

**Comment by stelcodes** [comment]
Here's my [derivation](https://github.com/stelcodes/zprint-nixos-derivation) for building zprint on NixOS!
https://github.com/stelcodes/zprint-nixos-derivation

Run `just build` or `nix-build` at the top level and you will get your binary. I'm submitting this to nixpkgs right now but it's my first attempt at Linux/NixOS packaging so it might take a while to get right.
