### ISSUE TITLE
Changelog dates since 0.2.11 seem wrong

### ISSUE THREAD

**Issue by OscarMarshall** [kkinnear/zprint#22]
Unless you have a time machine and your personal timeline is now situated a year in the past (in which case I have some bets I'd like you to place), I believe the changelog has incorrect dates starting with version 0.2.11.

**Comment by kkinnear** [comment]
Oscar,

Wow, you are so right!  The wonders of copy and paste.  Thanks, I'll fix them the next time I push stuff up. 

Thanks again -- Kim

**Comment by kkinnear** [comment]
I finally fixed this in some past release, and just now remembered to close the issue.
