### ISSUE TITLE
Newer rewrite-clj deprecates `edn*`

### ISSUE THREAD

**Issue by palfrey** [kkinnear/zprint#247]
See https://github.com/clj-commons/rewrite-clj/issues/178 which results in
```
----- ERROR -------------------------------------------------------------------
 File: jar:file:/home/palfrey/.m2/repository/zprint/zprint/1.2.3/zprint-1.2.3.jar!/zprint/zutil.cljc:200:50
--------------------------------------------------------------------------------
 197 |     (when (not (nil? nloc))
 198 |       (if (zthing? nloc) i (recur (zrightnws nloc) (inc i))))))
 199 |
 200 | (defn znl [] "Return a zloc which is a newline." (edn* (p/parse-string "\n")))
--------------------------------------------------------^-----------------------
null
rewrite-clj.zip/edn* is deprecated
{:warning :fn-deprecated, :line 200, :column 50, :msg "rewrite-clj.zip/edn* is deprecated", :shadow.build.compiler/warning-as-error true}
ExceptionInfo: rewrite-clj.zip/edn* is deprecated
```

**Comment by kkinnear** [comment]
Thanks for reporting this.  I'll update to the newer `rewrite-clj` and fix these functions in the next release.  Which I keep hoping is soon, but I also keep getting more bugs to fix.  I'm hoping in the next few weeks to do the `1.2.4` release.  Hopefully this deprecation isn't blocking you from using zprint?

**Comment by palfrey** [comment]
Nah, I've just downgraded the version of `rewrite-clj` my project is pulling in, as I didn't need any of the newer features anyways :)

**Comment by kkinnear** [comment]
In release `1.2.4`, just out now, the new `rewrite-clj` is used and `edn*` is gone.  Thanks for pointing this out, I wasn't paying attention to the changes in `rewrite-clj`!

**Comment by palfrey** [comment]
Thanks, this fixed my issue
