### ISSUE TITLE
Prefer cljs.core/*command-line-args* over lumo.core/*

### ISSUE THREAD

**Issue by SevereOverfl0w** [kkinnear/zprint#30]
`lumo.core/*command-line-args*` has been removed in favour of `cljs.core/*command-line-args*`

**Comment by kkinnear** [comment]
Thanks for letting me know about this change in `lumo`.  I haven't done much with `lumo` or `planck` since I got the `zprint-filter` working with the JVM, since in my environment the JVM is faster once I cache whatever the app-cds caches (which is pretty much like getting `lumo` or `planck` to cache the javascript).

I'll work on a new release.

**Comment by SevereOverfl0w** [comment]
Planck has also made the same change.

**Comment by kkinnear** [comment]
Sorry this is taking so long.  The change to my code is trivial, but the single underlying library I depend on requires an older version of cljs.tools.reader than is built into lumo, and uses an undocumented function which has changed.  I'm trying to work that out in several different ways, but it means that fix for this will take longer than I had hoped!

**Comment by SevereOverfl0w** [comment]
That's okay, there's no real rush from me.

On 22 September 2017 17:10:40 BST, Kim Kinnear <notifications@github.com> wrote:
>Sorry this is taking so long.  The change to my code is trivial, but
>the single underlying library I depend on requires an older version of
>cljs.tools.reader than is built into lumo, and uses an undocumented
>function which has changed.  I'm trying to work that out in several
>different ways, but it means that fix for this will take longer than I
>had hoped!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kkinnear/zprint/issues/30#issuecomment-331490879

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kkinnear** [comment]
This should all work in lumo 1.8.0-beta and planck 2.8.1 now.  Thanks for telling me about this, I haven't been keeping up with lumo and planck since I discovered appcds and the quick JVM startup.
