### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by radovanne3** [kkinnear/zprint#300]
Hello,
I am interested to know if it's possible to set up vertical alignment using zprint?

**Comment by kkinnear** [comment]
Maybe?  I don't know what you mean by vertical alignment?  At some level, all indentation is "vertical alignment", and certainly zprint can do that with several different approaches.  zprint will also do "justification" which will align pairs of things in columns.  

Perhaps if you give me an example of a function definition and what you would like it to look like, with your desired "vertical alignment", then I can tell you if zprint can do that.  

If you are referring to vertical alignment of non-code structures (say at the REPL), zprint can certainly do non-code formatting at the REPL.  So if you show me some data structure formatted the way that you would like it to be formatted, I can tell you if zprint can do that for you.

I'm glad to help figure out how to configure zprint to do what you want, and frequently make additions to the code to make it even more configurable to meet peoples needs.  I just need to know specifically what you are looking for.

Thanks for asking.

**Comment by radovanne3** [comment]
Hey,
Thanks for answer, I managed to find it in documentation.
I was refering to justification.
In let binding I want all values to be aligned.
So in case:
x                   "hello"
second-val   "hello"

But now there is a different issue, I am not able to get zprint on my machine.
I am using linux and I have downloaded zprintl-<version> but I can't seem to run it as a script as documentation says.

Sorry for my bad descriptions, I am relativly new at this..
And I appreciate your help.

**Comment by radovanne3** [comment]
My goal is to enable zprint inside null-ls neovim plugin and to set it up so it justifies.

**Comment by radovanne3** [comment]
I managed to get it done!
Keep up with the good work, as far as I know, this is only formatter that enables this kind of vertical alignment!
Thanks!

**Comment by kkinnear** [comment]
Sorry I wasn't much help with null-ls neovim, as I don't have any experience with it.  But I'm fascinated that you seem to have managed to integrate zprint with null-ls neovim.  Any chance you would be willing to share how you did that?  I'd like to try it out myself, and if I can replicate what you did, I'd add it to the documentation for zprint.  I'm sure others would like to do the same thing. Thanks!

**Comment by radovanne3** [comment]
Hey,
Btw I just noticed that I contacted you with two different github accounts...
@ned-at-obrizum is my work related account
I will share with you what I did.

I followed null-ls documentation and set zprint as wanted formatter when clojure client is active.
Then I just added .zprintrc in my home dir and set dictionary with required styles inside per your documentation and it just works haha

I will provide code snippets a little bit later.  :D

**Comment by radovanne3** [comment]
Hey Kim,

Sorry for the delay in getting back to you. I somehow thought our conversation had ended. I've made some tweaks to my .zprintrc file, mainly removing commas during formatting as they're considered bad practice in Clojure code. The style closely resembles Tonsky's Better Clojure Formatting (BCF), with just a few minor adjustments needed for proper indentation.

You can find the modified .zprintrc file here: https://github.com/radovanne3/neovim/blob/27e802c50bf66b7f98cbf28c093204f139db201f/.zprintrc

Since null-ls isn't maintained anymore, I've adapted my setup to work with none-ls instead. Here's how I've configured it: https://github.com/radovanne3/neovim/blob/27e802c50bf66b7f98cbf28c093204f139db201f/lua/verde/none-ls.lua

To avoid conflicts with the default zprint program on Mac, I've renamed your zprint executable to zprintm.

Given that the BCF style is, I guess, being used, perhaps it could be nice if you included as one of the predefined styles. This way, it would be easier for everyone to adopt.

Because of not being able to use BCF style in neovim before I used Emacs, but now I don't need anymore.
Maybe there are more people in same situation.

Either way, thank you for support!
