### ISSUE TITLE
Avoid hanging classname definitions with :hiccup style

### ISSUE THREAD

**Issue by qleguennec** [kkinnear/zprint#337]
Is it possible to avoid hanging `{:class [...]}` definitions with hiccup style and to respect `:width`?

For example,

```
{:class
               [(layout/full-width)
                (layout/pdt-s)
                (layout/mgb-xs)
                (layout/row)
                (layout/justc-space-b)
                (layout/alitems-center)]}
```

I would like the vector here to wrap on the same line, respecting `:width`, but still conserve the default behavior of `:hiccup` for other cases.

Thanks for the amazing library!

**Comment by kkinnear** [comment]
Good question. In looking at the `:hiccup` style, I'm not entirely sure why it always does `{:vector {:wrap? false}}` even when the vector isn't recognized as a `:hiccup` vector.  Seems like a possible bug to me, but it would take a good bit of time to research it to see if that is indeed true.  And it might be that people have come to expect it even if it is a bug.

In any case, here is what I think will work for you -- though without a more complete example, I'm not entirely sure.  The following solution uses a little known (and relatively late arriving) feature of zprint where you can specify the option map to use when formatting a particular key in a map.  

```
(czprint i337 {:parse-string? true :style :hiccup})
{:class [(layout/full-width)
         (layout/pdt-s)
         (layout/mgb-xs)
         (layout/row)
         (layout/justc-space-b)
         (layout/alitems-center)]}

(czprint i337 {:parse-string? true :style :hiccup :map {:key-value-options {:class {:vector {:wrap? true}}}}})
{:class [(layout/full-width) (layout/pdt-s) (layout/mgb-xs) (layout/row)
         (layout/justc-space-b) (layout/alitems-center)]}
```
Give this a try, and if it doesn't do what you want, perhaps you could give me a larger (more complete) example and I'll see what I can do.  I'm sure we can get what you want to work, it may take a try or two.

Thanks for asking!

**Comment by qleguennec** [comment]
@kkinnear It works perfectly, thank you!
