### ISSUE TITLE
Newlines in strings

### ISSUE THREAD

**Issue by mbossenbroek** [kkinnear/zprint#38]
Is there an option to produce multiline strings in the formatted output?

For example, both of these are equivalent strings:

`"foo\nbar"`

```
"foo
bar"
```

But zprinting either of them results in:

`"\"foo\\nbar\""`

Is there a way to have it actually put a newline in the formatted result instead of the escaped \n?

If not, could that be added?

Thanks,
Matt

**Comment by kkinnear** [comment]
I'm a bit confused as to what you are actually trying to do here.  Underneath, zprint is doing a `pr-str` for the string.  Internally that isn't always the best thing, so it has an internal option to just do a `str` for the string, which appears to be what you want.  That option isn't allowed for user input.  Yet.

But could you expand on the use case you have in mind?  What are you trying to do, and how is the current behavior messing you up?  Are you operating on structures with strings inside of them, or are you operating on Clojure(script) source code?  Your example was clearly operating on a simple string (what I would refer to as a structure and not Clojure source code), and I appreciate you boiling it down to something focused.

But a clearer picture of your use case and motivation for asking for this change would help me to understand the implications.  I want to make sure that any change I make will give you not only this specific behavior, but won't massively break something else that you are also depending on.  In addition to some words, a realistic example or two of what you are doing (and what you would like the result from zprint to look like) would help me a lot!

Thanks!

**Comment by mbossenbroek** [comment]
Sure - the use case is formatting arbitrary data structures, which are sometimes user code, but not always. Sometimes these will have very long strings with a lot of newlines in them. Think of a stack trace in a single string - with all of the lines joined by newlines.

There are multiple ways to format something like this. Today, formatting this

`{:foo {:bar ["a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np\nq\nr\ns\nt\nu\nv\nw\nx\ny\nz"]}}`

Would return this string:

`"{:foo {:bar [\"a\\nb\\nc\\nd\\ne\\nf\\ng\\nh\\ni\\nj\\nk\\nl\\nm\\nn\\no\\np\\nq\\nr\\ns\\nt\\nu\\nv\\nw\\nx\\ny\\nz\"]}}"`

Within this string there are escaped quotes, escaped backslashes, & the character 'n' to indicate where newlines go.

Another approach would be to return a string that contained actual newlines; something like this:

`"{:foo {:bar [\"a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np\nq\nr\ns\nt\nu\nv\nw\nx\ny\nz\"]}}"`

When printed, that string would look like the following:

```
{:foo {:bar ["a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z"]}}
```

Which is the desired behavior. In my use case, each of those letters would be a frame in a stack trace and actually take up more space.

I'm not 100% sure, but I don't think that just swapping out `pr-str` for `str` would do the trick. I believe you'd then lose the quotes around the string. The one in the string. My god this can get confusing...

Another interesting tautology that fell out of this is that these are actually equivalent string representations:

```
(= (read-string "\"\n\"")
   (read-string "\"\\n\""))
=> true
```

In the end, I believe that I'm looking for an option to do the following to all strings within the data structure after you call `pr-str` on them:

```
(clojure.string/replace (pr-str "foo\nbar") #"\\n" "\n")
=> "\"foo\nbar\""
```

Which just swaps out any escaped newlines with real ones. Then it would produce the output I'm looking for. I could potentially do this on the output I have today & would in theory only affect the strings within it, but that seems really hacky to me. It felt like having this in the tool would be a more principled approach.

Let me know if you need more info or examples.

Thanks!
Matt

**Comment by mbossenbroek** [comment]
Bonus points: make this behavior conditional on the length of the string. Short strings display a `\n`; long strings break.

**Comment by kkinnear** [comment]
Let me see what I can do.  I going to assume that you are using `zprint-str` or `czprint-str`.  Thanks for the explicit example of what you want, it will make it easier to figure out if I'm doing what you want.  I think I understand the details now, though I'm still a little hazy on the higher level use case.  But I have enough to information to move forward.

**Comment by coltnz** [comment]
Another user, pretty printing sql in edn config.

e.g.
`
 :query
   {:sql
      ["SELECT date, event_type.name AS classification... <long line>`

**Comment by kkinnear** [comment]
Well, after 4 years and a few months, I actually made the change for this.  My apologies, this really slipped through the cracks.  I obviously intended to work on it, and then got distracted and never looked at it again ... for years.  I'm sure you found some alternative, but in the highly unlikely event that you actually still care about this, the configuration `{:output {:real-le? true :real-le-length 20}}` are the things that control it.  Where `:real-le` stands for "real line ending", as it works for more than just newlines.  If you look in the `:output` section of the reference guide you will see the whole story.  Again, my apologies for totally ignoring this for years.

**Comment by mbossenbroek** [comment]
Thanks! This is still used, but the project has passed on to other maintainers now. I'll see if they can make use of this feature!
