### ISSUE TITLE
File comment API documentation is hard to find

### ISSUE THREAD

**Issue by kommen** [kkinnear/zprint#44]
The comments here are hard to find:

https://github.com/kkinnear/zprint/blob/139e3abf724ed655a9fe8d718a5b3548abefebd5/src/zprint/core.cljc#L638-L674

Is this a supported API and can they be moved to the readme?

**Comment by kkinnear** [comment]
This is currently documented in the lein-zprint readme (towards the end).  Is that how you are using it, or are you interested in the programmatic interface to this capability, where you process a file directly?

**Comment by kommen** [comment]
We're using `zprint-file-str` directly in two ways:

Emacs:
Hijacking the cider-nrepl backend used by `cider-format-*` functions to use `zprint-file-str`, see https://github.com/clojure-emacs/cider-nrepl/issues/453

Non-Emacs:
We start a socket server as part of the development environment, which passes the connection input stream to `zprint-file-str` and streams the result back. In a custom shell script we pass stdin via ncat to the socket server and the result from the socket server to stdout.

Both have the advantage of not having to boot a jvm.

**Comment by kkinnear** [comment]
Thanks for the information.  I used to do exactly the same thing with a server for formatting, also to avoid starting up a JVM.  Then my wife introduced me to app-cds and I built the [zprint-filter](https://github.com/kkinnear/zprint/blob/master/doc/filter.md) which starts in less than 1 second for me (using appcds of course).  If you haven't tried that, you might see what it does in your environment.  I find it nice just having it always there, and no requirement to start anything up to use it.  

In any case, yes, I expect to support the ;!zprint capability long term.  I'll move the documentation for it (well, duplicate it from lein-zprint) into the zprint readme.  I still have it on my todo list to add an options map to zprint-file-str based on the earlier issue.

Thanks again for your interest!

**Comment by kommen** [comment]
Yes we tried app-cds and it worked as you say. But we want to introduce a workflow in our project where the files are reformatted before every save and provide a go-mode and reason-mode like experience. For this we need something measured in ms rather than in seconds :)

Thank you for your awesome work!

**Comment by kkinnear** [comment]
Great, just wanted to make sure you knew about app-cds.  

I'm impressed with the progress you've made on the cider integration!  I'll reference the issue (since you kindly told people how to do it for now) in the readme, and when it gets all worked out I would very much welcome some words from you on how to configure cider to use zprint (which will make a lot more sense coming from you, as I'm not a cider user).

In looking at how you did the integration, would providing a zprint-file-str flavor with just one parameter (the file name) be helpful for people?  I could easily default the "zprint-specifier".  Just a thought.

**Comment by kommen** [comment]
> In looking at how you did the integration, would providing a zprint-file-str flavor with just one parameter (the file name) be helpful for people? I could easily default the "zprint-specifier". Just a thought.

Not sure. I think it is helpful to have to specify it so error messages are easier to reason about.

**Comment by kkinnear** [comment]
In 0.4.6, the ;!zprint API is now documented in the [readme](https://github.com/kkinnear/zprint/blob/master/doc/bang.md).  I also added the capability to have an options map input to zprint-file-string, and fixed it to not alter the stored options.  In addition, both zprint-file and zprint-file-string were added to the "official" API, as documented in the readme. Thanks for the suggestion!
