### ISSUE TITLE
Policy for inclusion in default :fn-map?

### ISSUE THREAD

**Issue by kommen** [kkinnear/zprint#50]
I wanted to ask what the policy is for adding fns to the default `:fn-map`?

For example, I would suggest to add [`match`](https://clojure.github.io/core.match/#clojure.core.match/match) with `:arg1-pair-body`, as I'd guess it's at least somewhat commonly used, but at the same time recognize this would be a never ending story.

**Comment by kkinnear** [comment]
The only "policy" is that as I run into functions that could look better, I add them to the `:fn-map` if there is already a formatting type that fits.  Sometimes I have to create a new formatting type, which is of varying difficulty.  You are right, this is never ending, but that is okay.  

I've never used `core.match`, and none of the code that I've tried zprint on has either, but I certainly agree, `match` should be `:arg1-pair-body`.  I'll make it so.  Looking at `core.match`, looks like `matchm` is another similar function, so I'll include that too.  There also seem to be `matchv` and `match-let`, but they don't seem to be documented, so I'll leave them out for now.  

Looking over the source for `core.match`, I can see that they could use zprint.  They really like to justify things.

If you find other functions that should be formatted specially, let me know and I'll add them.  The good news is that if people have already added them in their `~/.zprintrc`, their version will be used. 

Thanks for the suggestion!

**Comment by kkinnear** [comment]
Available in 0.4.8.
