### ISSUE TITLE
Prebuilt native-image binaries

### ISSUE THREAD

**Issue by martinklepsch** [kkinnear/zprint#66]
Hey @kkinnear, you probably looked into this: What would need to happen to provide prebuilt `zprint` binaries based on the GraalVM native-image stuff?

Is this a license issue or are we just missing a build system & distribution channel?
I would be happy to help with any of this but obviously can't fix a license 😄 

(via [this ClojureVerse thread on using `zprint` in pre-commit hooks](https://clojureverse.org/t/how-to-best-integrate-zprint-as-pre-commit-hook/3045/2))

**Comment by kkinnear** [comment]
Hi @martinklepsch, I already supply a prebuilt Linux zprint graalvm binary.  Look in the "Releases" tab on the front page.  The latest is `zprintl-0.4.10`.  I also supply the uberjar, in that release it was `zprint-filter-0.4.10`, and a script `build.zprintm` to allow you to easily create your own MacOS version version with the MacOS graalvm.  The MacOS graalvm has a different license than the Linux one, which I read as not allowing me to distribute a pre-built binary.  Of course, I could be wrong about that, but I'm trying to be reasonably careful.  At some point, they say they will do a community version of the MacOS graalvm distribution, and then I will distribute pre-built versions for both Linux and MacOs.

All of this is hopefully explained in: https://github.com/kkinnear/zprint/blob/master/doc/graalvm.md
but if there is something that you think I should add or change, don't hesitate to mention it!

Thanks for asking.

**Comment by martinklepsch** [comment]
Hey Kim, I’m not sure I’m misunderstanding but they seem to now provide a MacOS build of GraalVM CE: https://github.com/oracle/graal/releases

The instructions suggest to download the enterprise edition but I’m not entirely sure if that’s what you were referring to as different license or if there is something additional to that.

**Comment by martinklepsch** [comment]
Also thanks for providing the instructions to build yourself, I’m a happy zprint native-image user for a while now :)

**Comment by kkinnear** [comment]
Thanks Martin for pointing the CE edition of graalvm for MacOS.  I had recently downloaded the EE version of RC8, but somehow missed the CE version.  Looking at it now, I see that it showed up in August.  I just missed it.  Presuming that it works with zprint (which isn't a foregone conclusion, but that's a story for another time), the next release of zprint will include both `zprintl-0.4.11` and `zprintm-0.4.11`, which will be a great thing!  Thanks again for pointing that out.  The next zprint release will also work well with cljdoc. :-)

**Comment by kkinnear** [comment]
Prebuilt binaries for both Linux and MacOS available in zprint 0.4.11.  Thanks again for alerting me to the existence of the "ce" MacOS graalvm!
