### ISSUE TITLE
Does not introduce newlines between top-level forms

### ISSUE THREAD

**Issue by pesterhazy** [kkinnear/zprint#68]
```
$ ~/Downloads/zprintm-0.4.11 <<< $'(ns foo)(defn bar [ ] [1\n2])(defn baz [])'
(ns foo)(defn bar [] [1 2])(defn baz [])
```

Expected output

```
(ns foo)

(defn bar [] [1 2])

(defn baz [])
```

Is this the expected behavior, i.e. does zprint touch the arrangement of top-level forms?

**Comment by kkinnear** [comment]
Hello! 

You can get what I think you want, but for some reason I'm feeling pedantic today, so I'm going to have to build up to it slowly...

The zprint-filter (which what the graalvm binaries are created from) uses `zprint-file-str`.  The docstring starts out:
>   Take a string, which typically holds the contents of an entire
  file, but doesn't have to, and format the entire string, outputing
  a formatted string.  It respects white space at the top level,
  while completely ignoring it within all top level forms (typically
  defs and function definitions).  It allows comments at the top
  level, as well as in function definitions, and also supports
  ;!zprint directives at the top level. ...

You can see the whole thing here, not that there is any reason to do that other than to appreciate cljdoc:

https://cljdoc.org/d/zprint/zprint/0.4.11/api/zprint.core#zprint-file-str

So, yes, zprint-file-str respects white space at the top level, while largely ignoring it inside of the functions themselves.  I didn't imagine that I could figure out the "best" way to format top level stuff.  That said, you __can__ get what you appear to want.  Let me work through some examples.

First, if you put newlines in there, zprint-file-str will respect them:
```clojure
$ zprintm-0.4.11 <<< $'(ns foo)\n\n\n(defn bar [ ] [1\n2])(defn baz [])'
(ns foo)


(defn bar [] [1 2])(defn baz [])
$
```
If you don't have them, it won't put them in there (your original example):
```clojure
$ zprintm-0.4.11 <<< $'(ns foo)(defn bar [ ] [1\n2])(defn baz [])'
(ns foo)(defn bar [] [1 2])(defn baz [])
$
```
If you want a constant newline between top level forms, you can get it:
```clojure
$ zprintm-0.4.11 '{:parse {:interpose "\n"}}'  <<< $'(ns foo)(defn bar [ ] [1\n2])(defn baz [])'
(ns foo)
(defn bar [] [1 2])
(defn baz [])r$
```
Or you can have two newlines between top level forms, which seems to be what you were looking
```clojure
$ zprintm-0.4.11 '{:parse {:interpose "\n\n"}}'  <<< $'(ns foo)(defn bar [ ] [1\n2])(defn baz [])'
(ns foo)

(defn bar [] [1 2])

(defn baz [])$
```
Note, though, that the `{:parse {:interpose ...}}` construct will ignore any existing spacing between
top level forms:
```clojure
$ zprintm-0.4.11 '{:parse {:interpose "\n"}}' <<< $'(ns foo)\n\n\n(defn bar [ ] [1\n2])(defn baz [])'
(ns foo)
(defn bar [] [1 2])
(defn baz [])$
```
That's what it does today.  This is all currently supported, see here: https://github.com/kkinnear/zprint#parse-string-all
though you wouldn't know that `zprint-file-str` used the `:parse-string-all?` support. So I should document that.  There is also `{:left-space :drop}` and `{:left-space :keep}` that I apparently haven't documented, and should.  If that sounds interesting, let me know, and I'll give you some examples.

Hopefully this will give you what you are looking for.

**Comment by pesterhazy** [comment]
Great, I've added this to my unofficial zprint fanboy tutorial https://gist.github.com/pesterhazy/aac9638f1d22a3bc3339f95d1c607aed#top-level-newline-characters
