### ISSUE TITLE
Add sorting

### ISSUE THREAD

**Issue by tengstrand** [kkinnear/zprint#76]
Hi!

We use zprint in Polylith to generate and format Leiningen project.clj files.
Do you think it would be possible to add sorting to zprint in a way that is described here:
https://github.com/tengstrand/lein-polylith/issues/17

**Comment by kkinnear** [comment]
I could imagine a feature where arbitrary source transformations were supported.  I'd hand a function the structure and it would return a replacement structure.  If that function sorted the structure, then it would give you what you want.  I need to think a bit more on this, and I have some bugs to fix and a couple of other requests to deal with first, but I'll give it some thought and see what I can do.

**Comment by kkinnear** [comment]
@tengstrand, I've been looking at this issue, and have done the basic implementation to call out to a function that will allow reordering of the input.  I'm now trying to write the function that will reorder the input.

So I looked into the issue in polylith, and I find the comments there confusing.  I looked at the polylith code, and the way you are using zprint, using `zprint-file-str`, shouldn't ever change the order of anything.  It will format it differently for sure, but it doesn't change the order.  Until I get this new feature working, then it *will* change the order.  I just wanted to make that clear -- if someone thinks that zprint is changing the order of things in a `project.clj` file, they are mistaken.  At least for now.

**Comment by tengstrand** [comment]
Hi Kim!

Thank you so much with the help.
Maybe I misunderstood how to use zprint, and if so, I apologise.

The latest news is also that we probably will minimise the development
effort for
the current version of the plugin and instead start working on a total new
version.

It will get rid of the symbolic links and instead have one big project.clj
at the root.
We don't know yet if we will use zprint in this new version, so don't spend
too much
work on this if we are the only users of this feature.

Zprint has worked really well for us so thanks again!

/Joakim Tengstrand



Den ons 19 dec. 2018 kl 22:01 skrev Kim Kinnear <notifications@github.com>:

**Comment by kkinnear** [comment]
Added this capability in 0.4.14.  `{:style :sort-dependencies}` is how you use it.
