### ISSUE TITLE
Consider zprint.edn instead/along .zprinrc

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#83]
Hello again!

It seems like the community has kind of settled for the `.edn` suffix for configuration files that contain EDN...`figwheel-main.edn`, [`nrepl.edn`](https://nrepl.xyz/nrepl/usage/server.html#_server_options), `shadow-cljs.edn`, ...

Not a big deal but haven you considered calling the file `zprint.edn` or `.zprint.edn`?

The main reason is silly - Emacs users are probably already associating `.edn` to `clojure-mode` and will get full highlight. We can always tweak Emacs though, so again, not really a problem :smile: 

Feel free to just kill this one :hocho: 

:smile:

**Comment by arichiardi** [comment]
Sounds sensible to me :smile:

**Comment by kkinnear** [comment]
Fixed in 0.4.14.  Thanks for the idea.

**Comment by arichiardi** [comment]
Awesome thank you!
