### ISSUE TITLE
Newline insertion according to a configuration

### ISSUE THREAD

**Issue by vemv** [kkinnear/zprint#85]
Hi!

I'm considering adopting zprint.

I wonder if as of today it can turn `(if x y z)` into `(if x\n  y\n  z)` according to a user-tweakable configuration.

IOW, I want to establish+enforce some rules about what should include newlines, and where. More examples: `fn` (always insert a newline after the first _vector_), `when` (always insert a newline after whatever the first arg is). `if` is particularly interesting because it features _two_ newlines to be inserted.

Thoughts?

Thanks - Victor

**Comment by kkinnear** [comment]
Sure, you can configure that by changing the `:fn-map` for `if`, `when`, and `fn`:
```
zprint.core=> (czprint "(if a b c)" {:parse-string? true})
(if a b c)
nil
zprint.core=> (czprint "(if a b c)" {:parse-string? true :fn-map {"if" :arg1-force-nl}})
(if a
  b
  c)
nil
zprint.core=> (czprint "(fn [] a b c)" {:parse-string? true :fn-map {"fn" :arg1-force-nl}})
(fn []
  a
  b
  c)
```
The `{:parse-string? true}` is just to make it easier to show this formatting.  You would just put this:
```
{:fn-map {"if" :arg1-force-nl "when" :arg1-force-nl "fn" :arg1-force-nl}}
```
in your `~/.zprintrc`.   Let me know if you have any problems.

**Comment by vemv** [comment]
Thanks for the reply!

I see, https://github.com/kkinnear/zprint#function-classification-for-pretty-printing is helpful as well.

I'll try things out but in any case my original question is answered now.
