### ISSUE TITLE
Desired: no newline between a defn's name and arg vector

### ISSUE THREAD

**Issue by vemv** [kkinnear/zprint#86]
Hi there,

would it be possible to not insert a newline between a defn's name and its arg vector?

I did try studying the project's doc + source.

I think that for this to happen, something called `arg2-body` should be implemented? :)

Thanks - Victor

**Comment by vemv** [comment]
Understood!

Thank you for the explanation and putting this on the roadmap.

>  I can't see that anyone would really want the arg vector on the same line as the fn name and the doc-string anyway.

Yeah that would be very ugly.

So a smart behavior for what I want would be:

* Normal case: `defn foo [x y z]` by default (all in the same line)
* Docstring case: `defn foo "docstring" \n [x y z]` (newline after docstring)
* Long case: `defn fooooooooooo \n [xxxxxxxxxxxxxx yyyyyyyyy zzzzzzzzzzzzzzz]` (newline after the name, if otherwise :width would be surpassed)

That's exactly the 'algorithm' I follow myself manually, so it'd be awesome if zprint could automate it.

**Comment by kkinnear** [comment]
You can now do this in version 0.5.0, though it has been a long time in coming.  The key thing in making this work well was the implementation of `:next-inner`, which allows you to turn __off__ things that you just turned on to format a function -- thus changing only the "top level" of a function format, and not everything down inside of the function.

For example:

```clojure
 (def i86d
  "(defn thefn 
    [a b c] 
    (swap! this is (only a test to see what happens)) 
    (list a b c))") 

zprint.core=> (czprint i86d {:parse-string? true :fn-map {"defn" [:arg2 {:fn-force-nl #{:arg2} :next-inner {:remove {:fn-force-nl #{:arg2}}}}]}})
  (defn thefn [a b c]
    (swap! this is (only a test to see what happens))
    (list a b c))
```
I believe that this will do exactly what you want, in all of the cases.

**Comment by vemv** [comment]
Ace, thank you!

Right now I don't use zprint for my formatting needs, but next time the occasion arises, I'll be sure to keep in mind this one. 👍

**Comment by viebel** [comment]
I am also interested in formatting `defn` as it is suggested here.
Is there a simpler way to do that in July 2021 (last activity on this thread was on December 2019)?

**Comment by vemv** [comment]
Yes, :style :rod has been implemented following https://github.com/kkinnear/zprint/issues/170

(@kkinnear , sorry for the lack of input. I have a quite a lot on my plate right now)
