### ISSUE TITLE
native-image's check version option.

### ISSUE THREAD

**Issue by netpyoung** [kkinnear/zprint#94]
It will be good to have the option which can be check the version of itself.
```
zprint --version
```

**Comment by frou** [comment]
This is a good idea, since a lot of people will probably rename the downloaded binary (e.g. `zprintm-0.4.16`) to `zprint` before putting it on their `PATH`. After some time has passed, we're not going to remember what name the file had prior to renaming.

**Comment by kkinnear** [comment]
This is implemented in 0.5.0.  Thanks for the idea!
