### ISSUE TITLE
MacOS native-image changes international characters to `??`

### ISSUE THREAD

**Issue by huahaiy** [kkinnear/zprint#96]
This is the same issue as #78, and that was fixed for Linux, but the same problem exists in MacOS. I looked that the Mac build file, it already has `LC_ALL=C.UTF-8`, so I don't know what could be problems. Maybe it has something to do with Mac toolchain and that flag may not have intended effect.

**Comment by huahaiy** [comment]
I think this is a regression introduced recently. We didn't have these problems for version 0.4.13

**Comment by kkinnear** [comment]
I have built a macOS zprintm-0.4.15x, which comes from the same uberjar as the zprintm-0.4.15 in the release, but is built w/out the `LC...` on the command line.  I thought maybe I could attach it here, but I can't.  Looks like only text files are allowed.  Could I email it to you?   I see that your email is available on GitHub.

[By the way, I really enjoyed your talk at the Conj last fall.  I was there, and it was interesting to see the way that you all have fused the symbolic AI that brought me into Lisp a good while ago with the deep learning AI so prevalent today.]

**Comment by huahaiy** [comment]
Sure. Thanks for looking into it.

[I am glad that you like the talk. It was a fun conference. Hope to see you in the next Conj.]

**Comment by kkinnear** [comment]
Thanks or testing this. 

For the record, the result was that building without the `LC_` was that it works like it should work.  Which seems strange, but perhaps the two different versions of GraalVM handle this differently.  Or not, who knows?  Anyway, I'll build the macOS version w/out the `LC_` and the Linux version with the `LC_` until something else comes up.

**Comment by kkinnear** [comment]
This is changed (and hopefully fixed) in version 0.4.16.  I don't have a great way to test this, so I hope it makes things better and not worse.
