### ISSUE TITLE
minor change to README

### ISSUE THREAD

**Issue by bherrmann7** [kkinnear/zprint#97]
Hi Kim,

Could you change the README so that

"Add the following either to the $HOME/.clojure/deps.edn file or to a project deps.edn"

reads

"Add the following to the :aliases section of $HOME/.clojure/deps.edn file or to a project deps.edn"

and/or consider providing the following example..

```
$ cat > deps.edn
{:aliases {:zprint {:extra-deps {org.clojure/clojure #:mvn{:version "1.9.0"},
                                 zprint #:mvn{:version "0.4.13"}},
                    :main-opts ["-m" "zprint.main"]}},
 :deps {}}
^d
$ clj -A:zprint < deps.edn
```
Thanks...  I had not used the aliases part of deps.edn and didnt realize the :zprint key/value pair needed to go there.

Thanks, by the way, for this fantastic utility!

**Comment by kkinnear** [comment]
Thanks, Bob, for these great suggestions. I'm still relying on others for the information about how to use `clj` and `deps.edn`, as I've not yet added that to my personal workflow.  I'll make these changes for the next release.  Thanks for the positive feedback too, every bit helps!

**Comment by kkinnear** [comment]
Thanks for this, I put this in 0.4.16.
